-- FOR LAND BUILDING PROPERTY
CREATE PROC AccAtt @Code nvarchar(15)
AS
SELECT AH.ACCHEAD_NAME, AA.ACCATTRIBUTE_AREA_ENGINENO, AA.ACCATTRIBUTE_SIZE_CHASS FROM ACCOUNT_HEADS AS AH
INNER JOIN PARENT_HEADS ON AH.ACCPARENTHEAD_ID = PARENT_HEADS.PARENTHEAD_ID
INNER JOIN ACCOUNT_ATTRIBUTES AS AA ON AH.ACCHEAD_ID = AA.ACCHEAD_ID
WHERE PARENT_HEADS.PARENTHEAD_CODE = @Code
Go

-- FOR MOTOR & VEHICLES
CREATE PROC AccAtt_DepCar_DepYearly @Code nvarchar(15)
AS
SELECT AH.ACCHEAD_NAME, AA.ACCATTRIBUTE_AREA_ENGINENO, AA.ACCATTRIBUTE_SIZE_CHASS, DC.DEP_LIFE, DC.DEP_METHOD, DC.DEP_PURCHASEDATE, DC.DEP_RATE, DC.DEP_YEARLYRATE, DC.ACCATTRIBUTE_DEP_SALVAGE,
DY.YEARNO, DY.YEARRATE FROM ACCOUNT_HEADS AS AH
INNER JOIN PARENT_HEADS ON AH.ACCPARENTHEAD_ID = PARENT_HEADS.PARENTHEAD_ID
INNER JOIN ACCOUNT_ATTRIBUTES AS AA ON AH.ACCHEAD_ID = AA.ACCHEAD_ID
INNER JOIN DEPRICIATION_CARD AS DC ON DC.ACCHEAD_ID =  AH.ACCHEAD_ID
INNER JOIN DEPRICIATION_YEARLYRATES AS DY ON DY.DEPCARD_ID = DC.DEPCARD_ID
WHERE PARENT_HEADS.PARENTHEAD_CODE = @Code
Go

--FOR TRADE RECIVABLES AND TRADE PAYABLES
CREATE PROC AddCard @Code nvarchar(15)
AS
SELECT AH.ACCHEAD_NAME, AC.ADDRESS_LINE1, AC.ADDRESS_LINE2, AC.ADDRESS_LINE3, AC.CITY, AC.COUNTRY, AC.CR_LIMIT_AMOUNT, AC.CR_LIMIT_DAYS FROM ACCOUNT_HEADS AS AH
INNER JOIN PARENT_HEADS ON AH.ACCPARENTHEAD_ID = PARENT_HEADS.PARENTHEAD_ID
INNER JOIN ADDRESS_CARD AS AC ON AH.ACCHEAD_ID = AC.ACCHEAD_ID
WHERE PARENT_HEADS.PARENTHEAD_CODE = @Code
Go

-- PLANT & MACHINERY, OFFICE EQUP, HARDWARE ETC
CREATE PROC DepCard_DepYearly @Code nvarchar(15)
AS
SELECT ACCOUNT_HEADS.ACCHEAD_NAME, DC.DEP_LIFE, DC.DEP_METHOD, DC.DEP_PURCHASEDATE, DC.DEP_RATE, DC.DEP_YEARLYRATE, DC.ACCATTRIBUTE_DEP_SALVAGE,
DY.YEARNO, DY.YEARRATE FROM ACCOUNT_HEADS
INNER JOIN PARENT_HEADS ON ACCOUNT_HEADS.ACCPARENTHEAD_ID = PARENT_HEADS.PARENTHEAD_ID
INNER JOIN DEPRICIATION_CARD AS DC ON DC.ACCHEAD_ID =  ACCOUNT_HEADS.ACCHEAD_ID
INNER JOIN DEPRICIATION_YEARLYRATES AS DY ON DY.DEPCARD_ID = DC.DEPCARD_ID
WHERE PARENT_HEADS.PARENTHEAD_CODE = @Code
Go

Execute AccAtt '010-000-000-000';
Execute AccAtt_DepCar_DepYearly '010-000-000-000';
Execute AddCard '010-000-000-000';
Execute DepCard_DepYearly '010-000-000-000';