USE [master]
GO
/****** Object:  Database [ADS_2]    Script Date: 4/5/2021 11:17:56 PM ******/
CREATE DATABASE [ADS_2]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'ADS_2', FILENAME = N'D:\SQL_DATA\ADS_2.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'ADS_2_log', FILENAME = N'D:\SQL_DATA\ADS_2_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO
ALTER DATABASE [ADS_2] SET COMPATIBILITY_LEVEL = 130
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ADS_2].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [ADS_2] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [ADS_2] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [ADS_2] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [ADS_2] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [ADS_2] SET ARITHABORT OFF 
GO
ALTER DATABASE [ADS_2] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [ADS_2] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [ADS_2] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [ADS_2] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [ADS_2] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [ADS_2] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [ADS_2] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [ADS_2] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [ADS_2] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [ADS_2] SET  DISABLE_BROKER 
GO
ALTER DATABASE [ADS_2] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [ADS_2] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [ADS_2] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [ADS_2] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [ADS_2] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [ADS_2] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [ADS_2] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [ADS_2] SET RECOVERY FULL 
GO
ALTER DATABASE [ADS_2] SET  MULTI_USER 
GO
ALTER DATABASE [ADS_2] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [ADS_2] SET DB_CHAINING OFF 
GO
ALTER DATABASE [ADS_2] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [ADS_2] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [ADS_2] SET DELAYED_DURABILITY = DISABLED 
GO
EXEC sys.sp_db_vardecimal_storage_format N'ADS_2', N'ON'
GO
ALTER DATABASE [ADS_2] SET QUERY_STORE = OFF
GO
USE [ADS_2]
GO
/****** Object:  Table [dbo].[ACC_TRANS_BODY]    Script Date: 4/5/2021 11:17:56 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ACC_TRANS_BODY](
	[ATBODY_ID] [bigint] NOT NULL,
	[ATHEADER_ID] [bigint] NULL,
	[USER_ID] [bigint] NULL,
	[ACCHEAD_ID] [bigint] NULL,
	[ATBODY_DOCSNO] [int] NULL,
	[ATBODY_DATE_TRANS] [date] NULL,
	[ATBODY_DATE_SYSTEM] [date] NOT NULL,
	[ATBODY_TIME_SYSTEM] [time](7) NULL,
	[ATBODY_AMOUNT_TRANS] [float] NULL,
	[ATBODY_DATE_APP] [date] NULL,
 CONSTRAINT [PK_ACC_TRANS_BODY] PRIMARY KEY CLUSTERED 
(
	[ATBODY_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[ACC_TRANS_HEADER]    Script Date: 4/5/2021 11:17:56 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ACC_TRANS_HEADER](
	[ATHEADER_ID] [bigint] NULL,
	[ATHEADER_DOCNO] [nchar](10) NULL,
	[ATHEADER_DOCTYPE] [nchar](1) NULL,
	[AUTHORITY_ID] [bigint] NULL,
	[ATHEADER_APP_DATE] [date] NULL,
	[ATHEADER_APP_TIME] [time](7) NULL,
	[ATHEADER_APP_STATUS] [nchar](1) NULL,
	[ATHEADER_DOCPART] [nchar](255) NULL,
	[BOOKID] [bigint] NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[ACCOUNT_ATTRIBUTES]    Script Date: 4/5/2021 11:17:56 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ACCOUNT_ATTRIBUTES](
	[ACCATTRIBUTE_ID] [bigint] NOT NULL,
	[ACCHEAD_ID] [bigint] NULL,
	[ACCATTRIBUTE_TYPE] [nchar](1) NULL,
	[ACCATTRIBUTE_SIZE_CHASS] [nchar](20) NULL,
	[ACCATTRIBUTE_AREA_ENGINENO] [nchar](20) NULL,
 CONSTRAINT [PK_ACCOUNT_ATTRIBUTES] PRIMARY KEY CLUSTERED 
(
	[ACCATTRIBUTE_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[ACCOUNT_HEADS]    Script Date: 4/5/2021 11:17:56 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ACCOUNT_HEADS](
	[ACCHEAD_ID] [bigint] NOT NULL,
	[ACCPARENTHEAD_ID] [bigint] NOT NULL,
	[ACCHEAD_NAME] [nchar](60) NOT NULL,
	[ATTRIBUTE_CHOICE] [nchar](1) NULL,
	[DEPCARD_CHOICE] [nchar](1) NULL,
	[ADDCARD_CHOICE] [nchar](1) NULL,
	[PICTURE_CHOICE] [nchar](1) NULL,
 CONSTRAINT [PK_ACCOUNT_HEADS] PRIMARY KEY CLUSTERED 
(
	[ACCHEAD_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[ADDRESS_CARD]    Script Date: 4/5/2021 11:17:56 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ADDRESS_CARD](
	[ACC_ADDR_ID] [bigint] NOT NULL,
	[ACCHEAD_ID] [bigint] NULL,
	[ADDRESS_LINE1] [nchar](50) NULL,
	[ADDRESS_LINE2] [nchar](50) NULL,
	[ADDRESS_LINE3] [nchar](50) NULL,
	[CITY] [nchar](50) NULL,
	[COUNTRY] [nchar](50) NULL,
	[PHONE1] [nchar](15) NULL,
	[PHONE2] [nchar](15) NULL,
	[EMAIL] [nchar](50) NULL,
	[CR_LIMIT_AMOUNT] [float] NULL,
	[CR_LIMIT_DAYS] [int] NULL,
 CONSTRAINT [PK_ADDRESS_CARD] PRIMARY KEY CLUSTERED 
(
	[ACC_ADDR_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[APPROVAL_AUTHORITIES]    Script Date: 4/5/2021 11:17:56 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[APPROVAL_AUTHORITIES](
	[AUTHORITY_ID] [bigint] NOT NULL,
	[AUTHORITY_NAME] [nchar](30) NULL,
	[AUTHORITY_PASSWORD] [nchar](20) NULL,
	[APP_RV_AMOUNT] [float] NULL,
	[APP_PV_AMOUNT] [float] NULL,
	[APP_JV_AMOUNT] [float] NULL,
	[APP_ADJV_AMOUNT] [float] NULL,
	[APP_PROV_AMOUNT] [float] NULL,
	[APP_SALE_AMOUNT] [float] NULL,
	[APP_SALERET_AMOUNT] [float] NULL,
	[APP_PURCHASE_AMOUNT] [float] NULL,
	[APP_PURCHASERET_AMOUNT] [float] NULL,
 CONSTRAINT [PK_APPROVAL_AUTHORITIES] PRIMARY KEY CLUSTERED 
(
	[AUTHORITY_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[BOOKProperties]    Script Date: 4/5/2021 11:17:56 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[BOOKProperties](
	[BOOK_ID] [bigint] NOT NULL,
	[BOOK_TITLE] [nchar](60) NULL,
	[ACCHEAD_ID] [bigint] NULL,
	[BOOK_VOUCHER_NO_DR] [int] NULL,
	[BOOK_VOUCHER_PREFIX_DR] [nchar](5) NULL,
	[BOOK_VOUCHER_TITLE_DR] [nchar](60) NULL,
	[BOOK_VOUCHER_NO_CR] [int] NULL,
	[BOOK_VOUCHER_PREFIX_CR] [nchar](5) NULL,
	[BOOK_VOUCHER_TITLE_CR] [nchar](60) NULL,
 CONSTRAINT [PK_BOOKProperties] PRIMARY KEY CLUSTERED 
(
	[BOOK_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[DB_RECORD]    Script Date: 4/5/2021 11:17:56 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DB_RECORD](
	[DB_RECORD_ID] [bigint] NOT NULL,
	[DB_NAME] [nchar](10) NULL,
	[DB_COUNT] [bigint] NULL,
 CONSTRAINT [PK_DB_RECORD] PRIMARY KEY CLUSTERED 
(
	[DB_RECORD_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[DEPARTMENT_TABLE]    Script Date: 4/5/2021 11:17:56 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DEPARTMENT_TABLE](
	[DEP_ID] [bigint] NOT NULL,
	[DEP_NAME] [nvarchar](max) NULL,
 CONSTRAINT [PK_DEPARTMENT_TABLE] PRIMARY KEY CLUSTERED 
(
	[DEP_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[DEPRICIATION_CARD]    Script Date: 4/5/2021 11:17:56 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DEPRICIATION_CARD](
	[DEPCARD_ID] [bigint] NOT NULL,
	[ACCHEAD_ID] [bigint] NOT NULL,
	[DEP_PURCHASEDATE] [date] NULL,
	[DEP_RATE] [float] NULL,
	[DEP_METHOD] [nchar](1) NULL,
	[DEP_LIFE] [int] NULL,
	[ACCATTRIBUTE_DEP_SALVAGE] [float] NULL,
	[DEP_YEARLYRATE] [nchar](1) NULL,
 CONSTRAINT [PK_DEPRICIATION_CARD] PRIMARY KEY CLUSTERED 
(
	[DEPCARD_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[DEPRICIATION_YEARLYRATES]    Script Date: 4/5/2021 11:17:56 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DEPRICIATION_YEARLYRATES](
	[DEPCARD_RATE_ID] [bigint] NOT NULL,
	[DEPCARD_ID] [bigint] NOT NULL,
	[YEARNO] [int] NOT NULL,
	[YEARRATE] [float] NULL,
 CONSTRAINT [PK_DEPRICIATION_YEARLYRATES_1] PRIMARY KEY CLUSTERED 
(
	[DEPCARD_RATE_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[INV_TRANS_BODY]    Script Date: 4/5/2021 11:17:56 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[INV_TRANS_BODY](
	[ITBODY_ID] [bigint] NOT NULL,
	[ITHEADER_ID] [bigint] NOT NULL,
	[USER_ID] [bigint] NULL,
	[INVHEAD_ID] [bigint] NULL,
	[ITBODY_DOCSNO] [int] NULL,
	[ITBODY_DATE_TRANS] [date] NULL,
	[ITBODY_DATE_SYSTEM] [date] NULL,
	[ITBODY_TIME_SYSTEM] [time](7) NULL,
	[ITBODY_QUANTITY] [float] NULL,
	[ITBODY_QUANTITY_UNIT] [nchar](15) NULL,
	[ITBODY_RATE] [float] NULL,
	[ITBODY_RATE_UNIT] [nchar](15) NULL,
	[ITBODY_AMOUNT] [float] NULL,
	[ITBODY_DISCOUNT_RATE] [float] NULL,
	[ITBODY_DISCOUNT_AMOUNT] [float] NOT NULL,
	[ITBODY_QUANTITY_REJECTED] [float] NULL,
	[ITBODY_QUANTITY_ACCEPTED] [float] NULL,
 CONSTRAINT [PK_INV_TRANS_BODY] PRIMARY KEY CLUSTERED 
(
	[ITBODY_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[INV_TRANS_FOOTER]    Script Date: 4/5/2021 11:17:56 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[INV_TRANS_FOOTER](
	[ITHEADER_ID] [bigint] NOT NULL,
	[ATHEADER_ID] [bigint] NULL,
	[ACCHEAD_ID] [bigint] NULL,
	[ACCHEAD_AMOUNT] [float] NULL,
	[AMOUNT_ADD_DEDUCT] [nchar](1) NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[INV_TRANS_HEADER]    Script Date: 4/5/2021 11:17:56 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[INV_TRANS_HEADER](
	[ITHEADER_ID] [bigint] NOT NULL,
	[AUTHORITY_ID] [bigint] NULL,
	[ITHEADER_DOCNO] [nchar](10) NULL,
	[ITHEADER_DOCTYPE] [nchar](10) NULL,
	[ITHEADER_APP_DATE] [date] NULL,
	[ITHEADER_APP_TIME] [time](7) NULL,
	[ITEADER_APP_STATUS] [nchar](1) NULL,
	[ITHEADER_TRANSPORT_MO] [nchar](20) NULL,
	[ITHEADER_TRANSPORT_REF] [nchar](20) NULL,
 CONSTRAINT [PK_INV_TRANS_HEADER] PRIMARY KEY CLUSTERED 
(
	[ITHEADER_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[INVENTORY_ATTRIBUTES]    Script Date: 4/5/2021 11:17:56 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[INVENTORY_ATTRIBUTES](
	[INV_ATTR_ID] [bigint] NOT NULL,
	[INVHEAD_ID] [bigint] NOT NULL,
	[STOCK_UNIT] [nchar](15) NULL,
	[PACKING_UNIT] [nchar](15) NULL,
	[LOOSE_UNIT] [nchar](15) NULL,
	[RATE_PER_LOOSE_UNIT] [float] NULL,
	[RATE_PER_STOCK_UNIT] [float] NULL,
	[RATE_PER_PACKING_UNIT] [float] NULL,
	[RATE_PRICE_LOOSE_UNIT] [float] NULL,
	[RATE_PRICE_STOCK_UNIT] [float] NULL,
	[RATE_PRICE_PACKING_UNIT] [float] NULL,
	[BALANCE_LOOSE_UNIT] [float] NULL,
	[BALANCE_STOCK_UNIT] [float] NULL,
	[BALANCE_PACKING_UNIT] [float] NULL,
	[COST_LOOSE_UNIT] [float] NULL,
	[COST_STOCK_UNIT] [float] NULL,
	[COST_PACKING_UNIT] [float] NULL,
	[SALE_CR_ACC] [bigint] NULL,
	[PURCHASE_DR_ACC] [bigint] NULL,
	[CONSUMPTION_DR_ACC] [bigint] NULL,
	[PRODUCTION_DR_ACC] [bigint] NULL,
 CONSTRAINT [PK_INVENTORY_ATTRIBUTES] PRIMARY KEY CLUSTERED 
(
	[INV_ATTR_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[INVENTORY_HEADS]    Script Date: 4/5/2021 11:17:56 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[INVENTORY_HEADS](
	[INVHEAD_ID] [bigint] NOT NULL,
	[INVPARENTHEAD_ID] [bigint] NULL,
	[INVHEAD_NAME] [nchar](60) NULL,
	[INV_SPECIFICATION_CHOICE] [nchar](1) NULL,
	[INV_PICTURE_CHOICE] [nchar](1) NULL,
	[INV_CODE_PARTNO] [nchar](30) NULL,
 CONSTRAINT [PK_INVENTORY_HEADS] PRIMARY KEY CLUSTERED 
(
	[INVHEAD_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[INVENTORY_SPECIFICATIONS]    Script Date: 4/5/2021 11:17:56 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[INVENTORY_SPECIFICATIONS](
	[INVHEAD_ID] [bigint] NOT NULL,
	[INV_SPECIFICATIONS] [nchar](255) NULL,
 CONSTRAINT [PK_INVENTORY_SPECIFICATIONS] PRIMARY KEY CLUSTERED 
(
	[INVHEAD_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PARENT_HEADS]    Script Date: 4/5/2021 11:17:56 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PARENT_HEADS](
	[PARENTHEAD_ID] [bigint] NOT NULL,
	[PARENTHEAD_TYPE] [nchar](1) NULL,
	[PARENTHEAD_CODE] [nchar](15) NULL,
	[PARENTHEAD_TITLE] [nchar](60) NULL,
	[PARENTHEAD_TYPEII] [nvarchar](1) NULL,
 CONSTRAINT [PK_PARENT_HEADS] PRIMARY KEY CLUSTERED 
(
	[PARENTHEAD_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TAX_TABLE]    Script Date: 4/5/2021 11:17:56 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TAX_TABLE](
	[TAXID] [bigint] NOT NULL,
	[TAXNAME] [nvarchar](max) NULL,
	[TAXRATE_PERCENTAGE] [float] NULL,
	[TAXRATE_PERUNIT] [float] NULL,
	[TAXVALIDITY_FROM] [date] NULL,
	[TAXVALIDITY_TO] [date] NULL,
	[TAXACTION] [nchar](1) NULL,
 CONSTRAINT [PK_TAX_TABLE] PRIMARY KEY CLUSTERED 
(
	[TAXID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TERMS_AND_CONDITIONS]    Script Date: 4/5/2021 11:17:56 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TERMS_AND_CONDITIONS](
	[TnC_ID] [bigint] NOT NULL,
	[TnC_TEXT] [text] NULL,
	[TnC_DOC_ID] [bigint] NULL,
 CONSTRAINT [PK_TERMS_AND_CONDITIONS] PRIMARY KEY CLUSTERED 
(
	[TnC_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
INSERT [dbo].[ACCOUNT_HEADS] ([ACCHEAD_ID], [ACCPARENTHEAD_ID], [ACCHEAD_NAME], [ATTRIBUTE_CHOICE], [DEPCARD_CHOICE], [ADDCARD_CHOICE], [PICTURE_CHOICE]) VALUES (1, 20, N'Ali Asgar Textile Mill                                      ', N'0', N'0', N'1', N'1')
GO
INSERT [dbo].[ACCOUNT_HEADS] ([ACCHEAD_ID], [ACCPARENTHEAD_ID], [ACCHEAD_NAME], [ATTRIBUTE_CHOICE], [DEPCARD_CHOICE], [ADDCARD_CHOICE], [PICTURE_CHOICE]) VALUES (2, 20, N'Aazad Commission                                            ', N'0', N'0', N'1', N'0')
GO
INSERT [dbo].[ACCOUNT_HEADS] ([ACCHEAD_ID], [ACCPARENTHEAD_ID], [ACCHEAD_NAME], [ATTRIBUTE_CHOICE], [DEPCARD_CHOICE], [ADDCARD_CHOICE], [PICTURE_CHOICE]) VALUES (3, 40, N'Computer Choice                                             ', N'0', N'0', N'1', N'0')
GO
INSERT [dbo].[ACCOUNT_HEADS] ([ACCHEAD_ID], [ACCPARENTHEAD_ID], [ACCHEAD_NAME], [ATTRIBUTE_CHOICE], [DEPCARD_CHOICE], [ADDCARD_CHOICE], [PICTURE_CHOICE]) VALUES (4, 40, N'Virtual Cables                                              ', N'0', N'0', N'1', N'0')
GO
INSERT [dbo].[ACCOUNT_HEADS] ([ACCHEAD_ID], [ACCPARENTHEAD_ID], [ACCHEAD_NAME], [ATTRIBUTE_CHOICE], [DEPCARD_CHOICE], [ADDCARD_CHOICE], [PICTURE_CHOICE]) VALUES (5, 86, N'Telephone Expense                                           ', N'0', N'0', N'0', N'0')
GO
INSERT [dbo].[ACCOUNT_HEADS] ([ACCHEAD_ID], [ACCPARENTHEAD_ID], [ACCHEAD_NAME], [ATTRIBUTE_CHOICE], [DEPCARD_CHOICE], [ADDCARD_CHOICE], [PICTURE_CHOICE]) VALUES (6, 88, N'Office Supplies                                             ', N'0', N'0', N'0', N'0')
GO
INSERT [dbo].[ACCOUNT_HEADS] ([ACCHEAD_ID], [ACCPARENTHEAD_ID], [ACCHEAD_NAME], [ATTRIBUTE_CHOICE], [DEPCARD_CHOICE], [ADDCARD_CHOICE], [PICTURE_CHOICE]) VALUES (7, 88, N'Rent Expense                                                ', N'0', N'0', N'0', N'0')
GO
INSERT [dbo].[ACCOUNT_HEADS] ([ACCHEAD_ID], [ACCPARENTHEAD_ID], [ACCHEAD_NAME], [ATTRIBUTE_CHOICE], [DEPCARD_CHOICE], [ADDCARD_CHOICE], [PICTURE_CHOICE]) VALUES (8, 88, N'Electricity Expense                                         ', N'0', N'0', N'0', N'0')
GO
INSERT [dbo].[ACCOUNT_HEADS] ([ACCHEAD_ID], [ACCPARENTHEAD_ID], [ACCHEAD_NAME], [ATTRIBUTE_CHOICE], [DEPCARD_CHOICE], [ADDCARD_CHOICE], [PICTURE_CHOICE]) VALUES (9, 20, N'Habib Sugar Mills                                           ', N'0', N'0', N'1', N'0')
GO
INSERT [dbo].[ACCOUNT_HEADS] ([ACCHEAD_ID], [ACCPARENTHEAD_ID], [ACCHEAD_NAME], [ATTRIBUTE_CHOICE], [DEPCARD_CHOICE], [ADDCARD_CHOICE], [PICTURE_CHOICE]) VALUES (10, 101, N'Transportation cost                                         ', N'0', N'0', N'0', N'0')
GO
INSERT [dbo].[ACCOUNT_HEADS] ([ACCHEAD_ID], [ACCPARENTHEAD_ID], [ACCHEAD_NAME], [ATTRIBUTE_CHOICE], [DEPCARD_CHOICE], [ADDCARD_CHOICE], [PICTURE_CHOICE]) VALUES (11, 101, N'Frieght charges                                             ', N'0', N'0', N'0', N'0')
GO
INSERT [dbo].[ACCOUNT_HEADS] ([ACCHEAD_ID], [ACCPARENTHEAD_ID], [ACCHEAD_NAME], [ATTRIBUTE_CHOICE], [DEPCARD_CHOICE], [ADDCARD_CHOICE], [PICTURE_CHOICE]) VALUES (12, 78, N'Purchases Acc - Computer Hardware                           ', N'0', N'0', N'0', N'0')
GO
INSERT [dbo].[ACCOUNT_HEADS] ([ACCHEAD_ID], [ACCPARENTHEAD_ID], [ACCHEAD_NAME], [ATTRIBUTE_CHOICE], [DEPCARD_CHOICE], [ADDCARD_CHOICE], [PICTURE_CHOICE]) VALUES (13, 19, N'Bank Al Habib Acc                                           ', N'0', N'0', N'0', N'0')
GO
INSERT [dbo].[ACCOUNT_HEADS] ([ACCHEAD_ID], [ACCPARENTHEAD_ID], [ACCHEAD_NAME], [ATTRIBUTE_CHOICE], [DEPCARD_CHOICE], [ADDCARD_CHOICE], [PICTURE_CHOICE]) VALUES (14, 20, N'INARA ACCOUNT                                               ', N'0', N'0', N'0', N'0')
GO
INSERT [dbo].[ACCOUNT_HEADS] ([ACCHEAD_ID], [ACCPARENTHEAD_ID], [ACCHEAD_NAME], [ATTRIBUTE_CHOICE], [DEPCARD_CHOICE], [ADDCARD_CHOICE], [PICTURE_CHOICE]) VALUES (15, 101, N'Experiment                                                  ', N'0', N'0', N'0', N'0')
GO
INSERT [dbo].[ACCOUNT_HEADS] ([ACCHEAD_ID], [ACCPARENTHEAD_ID], [ACCHEAD_NAME], [ATTRIBUTE_CHOICE], [DEPCARD_CHOICE], [ADDCARD_CHOICE], [PICTURE_CHOICE]) VALUES (16, 101, N'Experiment2                                                 ', N'0', N'0', N'0', N'0')
GO
INSERT [dbo].[ADDRESS_CARD] ([ACC_ADDR_ID], [ACCHEAD_ID], [ADDRESS_LINE1], [ADDRESS_LINE2], [ADDRESS_LINE3], [CITY], [COUNTRY], [PHONE1], [PHONE2], [EMAIL], [CR_LIMIT_AMOUNT], [CR_LIMIT_DAYS]) VALUES (1, 3, N'Shop No. 1, Toshi Square,                         ', N' University Rd, Block 13 B Gulshan-e-Iqbal        ', NULL, N'Karachi                                           ', N'Pakistan                                          ', N'03005627889    ', NULL, N'computerchoice@gmail.com                          ', 125000, 54)
GO
INSERT [dbo].[BOOKProperties] ([BOOK_ID], [BOOK_TITLE], [ACCHEAD_ID], [BOOK_VOUCHER_NO_DR], [BOOK_VOUCHER_PREFIX_DR], [BOOK_VOUCHER_TITLE_DR], [BOOK_VOUCHER_NO_CR], [BOOK_VOUCHER_PREFIX_CR], [BOOK_VOUCHER_TITLE_CR]) VALUES (1, N'Bank Book                                                   ', 13, 0, N'BDR- ', N'Bank Receipt Voucher                                        ', 0, N'BCR- ', N'Bank Payment Voucher                                        ')
GO
INSERT [dbo].[DEPARTMENT_TABLE] ([DEP_ID], [DEP_NAME]) VALUES (0, N'UNDEFINED')
GO
INSERT [dbo].[INVENTORY_ATTRIBUTES] ([INV_ATTR_ID], [INVHEAD_ID], [STOCK_UNIT], [PACKING_UNIT], [LOOSE_UNIT], [RATE_PER_LOOSE_UNIT], [RATE_PER_STOCK_UNIT], [RATE_PER_PACKING_UNIT], [RATE_PRICE_LOOSE_UNIT], [RATE_PRICE_STOCK_UNIT], [RATE_PRICE_PACKING_UNIT], [BALANCE_LOOSE_UNIT], [BALANCE_STOCK_UNIT], [BALANCE_PACKING_UNIT], [COST_LOOSE_UNIT], [COST_STOCK_UNIT], [COST_PACKING_UNIT], [SALE_CR_ACC], [PURCHASE_DR_ACC], [CONSUMPTION_DR_ACC], [PRODUCTION_DR_ACC]) VALUES (1, 1, N'ltr            ', N'ltr            ', N'ltr            ', 150, 150, 150, NULL, 150, 150, 150, 150, 150, 150, 150, 150, 12, 13, 14, 15)
GO
INSERT [dbo].[INVENTORY_ATTRIBUTES] ([INV_ATTR_ID], [INVHEAD_ID], [STOCK_UNIT], [PACKING_UNIT], [LOOSE_UNIT], [RATE_PER_LOOSE_UNIT], [RATE_PER_STOCK_UNIT], [RATE_PER_PACKING_UNIT], [RATE_PRICE_LOOSE_UNIT], [RATE_PRICE_STOCK_UNIT], [RATE_PRICE_PACKING_UNIT], [BALANCE_LOOSE_UNIT], [BALANCE_STOCK_UNIT], [BALANCE_PACKING_UNIT], [COST_LOOSE_UNIT], [COST_STOCK_UNIT], [COST_PACKING_UNIT], [SALE_CR_ACC], [PURCHASE_DR_ACC], [CONSUMPTION_DR_ACC], [PRODUCTION_DR_ACC]) VALUES (2, 2, N'pieces         ', NULL, NULL, NULL, 60000, NULL, NULL, NULL, NULL, NULL, 10, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
GO
INSERT [dbo].[INVENTORY_HEADS] ([INVHEAD_ID], [INVPARENTHEAD_ID], [INVHEAD_NAME], [INV_SPECIFICATION_CHOICE], [INV_PICTURE_CHOICE], [INV_CODE_PARTNO]) VALUES (1, 103, N'Taizaab                                                     ', N'1', N'0', N'0                             ')
GO
INSERT [dbo].[INVENTORY_HEADS] ([INVHEAD_ID], [INVPARENTHEAD_ID], [INVHEAD_NAME], [INV_SPECIFICATION_CHOICE], [INV_PICTURE_CHOICE], [INV_CODE_PARTNO]) VALUES (2, 131, N'Monitors                                                    ', N'0', N'0', N'0                             ')
GO
INSERT [dbo].[INVENTORY_SPECIFICATIONS] ([INVHEAD_ID], [INV_SPECIFICATIONS]) VALUES (1, N'Bohot Strong                                                                                                                                                                                                                                                   ')
GO
INSERT [dbo].[PARENT_HEADS] ([PARENTHEAD_ID], [PARENTHEAD_TYPE], [PARENTHEAD_CODE], [PARENTHEAD_TITLE], [PARENTHEAD_TYPEII]) VALUES (1, N'A', N'010-000-000-000', N'NON CURRENT ASSETS                                          ', N'B')
GO
INSERT [dbo].[PARENT_HEADS] ([PARENTHEAD_ID], [PARENTHEAD_TYPE], [PARENTHEAD_CODE], [PARENTHEAD_TITLE], [PARENTHEAD_TYPEII]) VALUES (2, N'A', N'010-001-000-000', N'LAND                                                        ', N'B')
GO
INSERT [dbo].[PARENT_HEADS] ([PARENTHEAD_ID], [PARENTHEAD_TYPE], [PARENTHEAD_CODE], [PARENTHEAD_TITLE], [PARENTHEAD_TYPEII]) VALUES (3, N'A', N'010-002-000-000', N'BUILDING                                                    ', N'B')
GO
INSERT [dbo].[PARENT_HEADS] ([PARENTHEAD_ID], [PARENTHEAD_TYPE], [PARENTHEAD_CODE], [PARENTHEAD_TITLE], [PARENTHEAD_TYPEII]) VALUES (4, N'A', N'010-003-000-000', N'PLANT AND MACHINERY                                         ', N'B')
GO
INSERT [dbo].[PARENT_HEADS] ([PARENTHEAD_ID], [PARENTHEAD_TYPE], [PARENTHEAD_CODE], [PARENTHEAD_TITLE], [PARENTHEAD_TYPEII]) VALUES (5, N'A', N'010-004-000-000', N'OFFICE EQUIPMENTS                                           ', N'B')
GO
INSERT [dbo].[PARENT_HEADS] ([PARENTHEAD_ID], [PARENTHEAD_TYPE], [PARENTHEAD_CODE], [PARENTHEAD_TITLE], [PARENTHEAD_TYPEII]) VALUES (6, N'A', N'010-005-000-000', N'AIR CONDITIONERS AND REFRIGERATORS                          ', N'B')
GO
INSERT [dbo].[PARENT_HEADS] ([PARENTHEAD_ID], [PARENTHEAD_TYPE], [PARENTHEAD_CODE], [PARENTHEAD_TITLE], [PARENTHEAD_TYPEII]) VALUES (7, N'A', N'010-006-000-000', N'COMPUTER HARDWARE AND PERIPHERIALS                          ', N'B')
GO
INSERT [dbo].[PARENT_HEADS] ([PARENTHEAD_ID], [PARENTHEAD_TYPE], [PARENTHEAD_CODE], [PARENTHEAD_TITLE], [PARENTHEAD_TYPEII]) VALUES (8, N'A', N'010-007-000-000', N'MOTOR AND VEHICLES                                          ', N'B')
GO
INSERT [dbo].[PARENT_HEADS] ([PARENTHEAD_ID], [PARENTHEAD_TYPE], [PARENTHEAD_CODE], [PARENTHEAD_TITLE], [PARENTHEAD_TYPEII]) VALUES (9, N'A', N'010-010-000-000', N'INVESTMENTS                                                 ', N'B')
GO
INSERT [dbo].[PARENT_HEADS] ([PARENTHEAD_ID], [PARENTHEAD_TYPE], [PARENTHEAD_CODE], [PARENTHEAD_TITLE], [PARENTHEAD_TYPEII]) VALUES (10, N'A', N'010-010-001-000', N'INSURANCE POLICIES                                          ', N'B')
GO
INSERT [dbo].[PARENT_HEADS] ([PARENTHEAD_ID], [PARENTHEAD_TYPE], [PARENTHEAD_CODE], [PARENTHEAD_TITLE], [PARENTHEAD_TYPEII]) VALUES (11, N'A', N'010-010-002-000', N'STOCK/SHARES                                                ', N'B')
GO
INSERT [dbo].[PARENT_HEADS] ([PARENTHEAD_ID], [PARENTHEAD_TYPE], [PARENTHEAD_CODE], [PARENTHEAD_TITLE], [PARENTHEAD_TYPEII]) VALUES (12, N'A', N'010-010-003-000', N'PROPERTY                                                    ', N'B')
GO
INSERT [dbo].[PARENT_HEADS] ([PARENTHEAD_ID], [PARENTHEAD_TYPE], [PARENTHEAD_CODE], [PARENTHEAD_TITLE], [PARENTHEAD_TYPEII]) VALUES (13, N'A', N'010-010-004-000', N'BANK CERTIFICATES                                           ', N'B')
GO
INSERT [dbo].[PARENT_HEADS] ([PARENTHEAD_ID], [PARENTHEAD_TYPE], [PARENTHEAD_CODE], [PARENTHEAD_TITLE], [PARENTHEAD_TYPEII]) VALUES (14, N'A', N'010-010-005-000', N'FIXED DEPOSITS                                              ', N'B')
GO
INSERT [dbo].[PARENT_HEADS] ([PARENTHEAD_ID], [PARENTHEAD_TYPE], [PARENTHEAD_CODE], [PARENTHEAD_TITLE], [PARENTHEAD_TYPEII]) VALUES (15, N'A', N'010-050-000-000', N'INTANGIBLE ASSETS                                           ', N'B')
GO
INSERT [dbo].[PARENT_HEADS] ([PARENTHEAD_ID], [PARENTHEAD_TYPE], [PARENTHEAD_CODE], [PARENTHEAD_TITLE], [PARENTHEAD_TYPEII]) VALUES (16, N'A', N'010-090-000-000', N'ALLOWANCE FOR DEPRICIATION                                  ', N'B')
GO
INSERT [dbo].[PARENT_HEADS] ([PARENTHEAD_ID], [PARENTHEAD_TYPE], [PARENTHEAD_CODE], [PARENTHEAD_TITLE], [PARENTHEAD_TYPEII]) VALUES (17, N'A', N'020-000-000-000', N'CURRENT ASSETS                                              ', N'B')
GO
INSERT [dbo].[PARENT_HEADS] ([PARENTHEAD_ID], [PARENTHEAD_TYPE], [PARENTHEAD_CODE], [PARENTHEAD_TITLE], [PARENTHEAD_TYPEII]) VALUES (18, N'A', N'020-001-000-000', N'CASH ACCOUNTS                                               ', N'B')
GO
INSERT [dbo].[PARENT_HEADS] ([PARENTHEAD_ID], [PARENTHEAD_TYPE], [PARENTHEAD_CODE], [PARENTHEAD_TITLE], [PARENTHEAD_TYPEII]) VALUES (19, N'A', N'020-002-000-000', N'BANK ACCOUNTS                                               ', N'B')
GO
INSERT [dbo].[PARENT_HEADS] ([PARENTHEAD_ID], [PARENTHEAD_TYPE], [PARENTHEAD_CODE], [PARENTHEAD_TITLE], [PARENTHEAD_TYPEII]) VALUES (20, N'A', N'020-003-000-000', N'ACCOUNT RECEIVABLES/TRADE RECEIVABLES/ DEBTORS              ', N'B')
GO
INSERT [dbo].[PARENT_HEADS] ([PARENTHEAD_ID], [PARENTHEAD_TYPE], [PARENTHEAD_CODE], [PARENTHEAD_TITLE], [PARENTHEAD_TYPEII]) VALUES (21, N'A', N'020-004-000-000', N'ACCURED REVENUE                                             ', N'B')
GO
INSERT [dbo].[PARENT_HEADS] ([PARENTHEAD_ID], [PARENTHEAD_TYPE], [PARENTHEAD_CODE], [PARENTHEAD_TITLE], [PARENTHEAD_TYPEII]) VALUES (22, N'A', N'020-005-000-000', N'CLOSING STOCKS                                              ', N'B')
GO
INSERT [dbo].[PARENT_HEADS] ([PARENTHEAD_ID], [PARENTHEAD_TYPE], [PARENTHEAD_CODE], [PARENTHEAD_TITLE], [PARENTHEAD_TYPEII]) VALUES (23, N'A', N'020-005-001-000', N'FINISHED GOODS                                              ', N'B')
GO
INSERT [dbo].[PARENT_HEADS] ([PARENTHEAD_ID], [PARENTHEAD_TYPE], [PARENTHEAD_CODE], [PARENTHEAD_TITLE], [PARENTHEAD_TYPEII]) VALUES (24, N'A', N'020-005-002-000', N'WORK-IN-PROGRESS                                            ', N'B')
GO
INSERT [dbo].[PARENT_HEADS] ([PARENTHEAD_ID], [PARENTHEAD_TYPE], [PARENTHEAD_CODE], [PARENTHEAD_TITLE], [PARENTHEAD_TYPEII]) VALUES (25, N'A', N'020-005-003-000', N'RAW MATERIALS                                               ', N'B')
GO
INSERT [dbo].[PARENT_HEADS] ([PARENTHEAD_ID], [PARENTHEAD_TYPE], [PARENTHEAD_CODE], [PARENTHEAD_TITLE], [PARENTHEAD_TYPEII]) VALUES (26, N'A', N'020-005-004-000', N'PACKING MATERIALS                                           ', N'B')
GO
INSERT [dbo].[PARENT_HEADS] ([PARENTHEAD_ID], [PARENTHEAD_TYPE], [PARENTHEAD_CODE], [PARENTHEAD_TITLE], [PARENTHEAD_TYPEII]) VALUES (27, N'A', N'020-005-005-000', N'CONSUMABLE GOODS                                            ', N'B')
GO
INSERT [dbo].[PARENT_HEADS] ([PARENTHEAD_ID], [PARENTHEAD_TYPE], [PARENTHEAD_CODE], [PARENTHEAD_TITLE], [PARENTHEAD_TYPEII]) VALUES (28, N'A', N'020-006-000-000', N'OTHER RECEIVABLES                                           ', N'B')
GO
INSERT [dbo].[PARENT_HEADS] ([PARENTHEAD_ID], [PARENTHEAD_TYPE], [PARENTHEAD_CODE], [PARENTHEAD_TITLE], [PARENTHEAD_TYPEII]) VALUES (29, N'A', N'020-006-001-000', N'ADVANCE TO STAFF                                            ', N'B')
GO
INSERT [dbo].[PARENT_HEADS] ([PARENTHEAD_ID], [PARENTHEAD_TYPE], [PARENTHEAD_CODE], [PARENTHEAD_TITLE], [PARENTHEAD_TYPEII]) VALUES (30, N'A', N'020-006-002-000', N'BORROWERS/LOANEES                                           ', N'B')
GO
INSERT [dbo].[PARENT_HEADS] ([PARENTHEAD_ID], [PARENTHEAD_TYPE], [PARENTHEAD_CODE], [PARENTHEAD_TITLE], [PARENTHEAD_TYPEII]) VALUES (31, N'A', N'020-006-003-000', N'PREPAYMENTS                                                 ', N'B')
GO
INSERT [dbo].[PARENT_HEADS] ([PARENTHEAD_ID], [PARENTHEAD_TYPE], [PARENTHEAD_CODE], [PARENTHEAD_TITLE], [PARENTHEAD_TYPEII]) VALUES (32, N'A', N'020-006-004-000', N'REFUND OF TAXES                                             ', N'B')
GO
INSERT [dbo].[PARENT_HEADS] ([PARENTHEAD_ID], [PARENTHEAD_TYPE], [PARENTHEAD_CODE], [PARENTHEAD_TITLE], [PARENTHEAD_TYPEII]) VALUES (33, N'A', N'020-006-005-000', N'SECURITY DEPOSITS                                           ', N'B')
GO
INSERT [dbo].[PARENT_HEADS] ([PARENTHEAD_ID], [PARENTHEAD_TYPE], [PARENTHEAD_CODE], [PARENTHEAD_TITLE], [PARENTHEAD_TYPEII]) VALUES (34, N'A', N'020-006-006-000', N'ADVANCE TO OTHERS                                           ', N'B')
GO
INSERT [dbo].[PARENT_HEADS] ([PARENTHEAD_ID], [PARENTHEAD_TYPE], [PARENTHEAD_CODE], [PARENTHEAD_TITLE], [PARENTHEAD_TYPEII]) VALUES (35, N'A', N'020-007-000-000', N'IMPORT GOODS IN TRANSIT                                     ', N'B')
GO
INSERT [dbo].[PARENT_HEADS] ([PARENTHEAD_ID], [PARENTHEAD_TYPE], [PARENTHEAD_CODE], [PARENTHEAD_TITLE], [PARENTHEAD_TYPEII]) VALUES (36, N'A', N'020-008-000-000', N'SHORT TERM INVESTMENT                                       ', N'B')
GO
INSERT [dbo].[PARENT_HEADS] ([PARENTHEAD_ID], [PARENTHEAD_TYPE], [PARENTHEAD_CODE], [PARENTHEAD_TITLE], [PARENTHEAD_TYPEII]) VALUES (37, N'A', N'020-009-000-000', N'SHORT TERM LENDING                                          ', N'B')
GO
INSERT [dbo].[PARENT_HEADS] ([PARENTHEAD_ID], [PARENTHEAD_TYPE], [PARENTHEAD_CODE], [PARENTHEAD_TITLE], [PARENTHEAD_TYPEII]) VALUES (38, N'A', N'030-000-000-000', N'CURRENT LIABILITIES                                         ', N'B')
GO
INSERT [dbo].[PARENT_HEADS] ([PARENTHEAD_ID], [PARENTHEAD_TYPE], [PARENTHEAD_CODE], [PARENTHEAD_TITLE], [PARENTHEAD_TYPEII]) VALUES (39, N'A', N'030-001-000-000', N'BANK OVERDRAFTS AND LOANS                                   ', N'B')
GO
INSERT [dbo].[PARENT_HEADS] ([PARENTHEAD_ID], [PARENTHEAD_TYPE], [PARENTHEAD_CODE], [PARENTHEAD_TITLE], [PARENTHEAD_TYPEII]) VALUES (40, N'A', N'030-002-000-000', N'ACCOUNT PAYBLES/ TRADE PAYABLES/ CREDITORS                  ', N'B')
GO
INSERT [dbo].[PARENT_HEADS] ([PARENTHEAD_ID], [PARENTHEAD_TYPE], [PARENTHEAD_CODE], [PARENTHEAD_TITLE], [PARENTHEAD_TYPEII]) VALUES (41, N'A', N'030-003-000-000', N'ACCRUED EXPENDITURE/ EXPENDITURE PAYABLES                   ', N'B')
GO
INSERT [dbo].[PARENT_HEADS] ([PARENTHEAD_ID], [PARENTHEAD_TYPE], [PARENTHEAD_CODE], [PARENTHEAD_TITLE], [PARENTHEAD_TYPEII]) VALUES (42, N'A', N'030-006-000-000', N'OTHER PAYABLES                                              ', N'B')
GO
INSERT [dbo].[PARENT_HEADS] ([PARENTHEAD_ID], [PARENTHEAD_TYPE], [PARENTHEAD_CODE], [PARENTHEAD_TITLE], [PARENTHEAD_TYPEII]) VALUES (43, N'A', N'030-006-001-000', N'ADVANCE RECEIPTS                                            ', N'B')
GO
INSERT [dbo].[PARENT_HEADS] ([PARENTHEAD_ID], [PARENTHEAD_TYPE], [PARENTHEAD_CODE], [PARENTHEAD_TITLE], [PARENTHEAD_TYPEII]) VALUES (44, N'A', N'030-006-002-000', N'SECURITY RECEIPTS                                           ', N'B')
GO
INSERT [dbo].[PARENT_HEADS] ([PARENTHEAD_ID], [PARENTHEAD_TYPE], [PARENTHEAD_CODE], [PARENTHEAD_TITLE], [PARENTHEAD_TYPEII]) VALUES (45, N'A', N'030-006-003-000', N'TAXES PAYABLE                                               ', N'B')
GO
INSERT [dbo].[PARENT_HEADS] ([PARENTHEAD_ID], [PARENTHEAD_TYPE], [PARENTHEAD_CODE], [PARENTHEAD_TITLE], [PARENTHEAD_TYPEII]) VALUES (46, N'A', N'030-006-004-000', N'SHORT TERM PROVISIONS                                       ', N'B')
GO
INSERT [dbo].[PARENT_HEADS] ([PARENTHEAD_ID], [PARENTHEAD_TYPE], [PARENTHEAD_CODE], [PARENTHEAD_TITLE], [PARENTHEAD_TYPEII]) VALUES (47, N'A', N'030-007-000-000', N'EXPORT GOODS IN TRANSIT                                     ', N'B')
GO
INSERT [dbo].[PARENT_HEADS] ([PARENTHEAD_ID], [PARENTHEAD_TYPE], [PARENTHEAD_CODE], [PARENTHEAD_TITLE], [PARENTHEAD_TYPEII]) VALUES (48, N'A', N'030-009-000-000', N'SHORT TERM BORROWINGS                                       ', N'B')
GO
INSERT [dbo].[PARENT_HEADS] ([PARENTHEAD_ID], [PARENTHEAD_TYPE], [PARENTHEAD_CODE], [PARENTHEAD_TITLE], [PARENTHEAD_TYPEII]) VALUES (49, N'A', N'030-010-000-000', N'PROCESSING UNITS                                            ', N'B')
GO
INSERT [dbo].[PARENT_HEADS] ([PARENTHEAD_ID], [PARENTHEAD_TYPE], [PARENTHEAD_CODE], [PARENTHEAD_TITLE], [PARENTHEAD_TYPEII]) VALUES (50, N'A', N'030-020-000-000', N'CONTRACTORS AND CONSULTANTS                                 ', N'B')
GO
INSERT [dbo].[PARENT_HEADS] ([PARENTHEAD_ID], [PARENTHEAD_TYPE], [PARENTHEAD_CODE], [PARENTHEAD_TITLE], [PARENTHEAD_TYPEII]) VALUES (51, N'A', N'030-030-000-000', N'SALES PERSON/ BROKERS/ AGENTS                               ', N'B')
GO
INSERT [dbo].[PARENT_HEADS] ([PARENTHEAD_ID], [PARENTHEAD_TYPE], [PARENTHEAD_CODE], [PARENTHEAD_TITLE], [PARENTHEAD_TYPEII]) VALUES (52, N'A', N'040-000-000-000', N'NON CURRENT LIABILITES                                      ', N'B')
GO
INSERT [dbo].[PARENT_HEADS] ([PARENTHEAD_ID], [PARENTHEAD_TYPE], [PARENTHEAD_CODE], [PARENTHEAD_TITLE], [PARENTHEAD_TYPEII]) VALUES (53, N'A', N'040-010-000-000', N'LONG TERM LOANS                                             ', N'B')
GO
INSERT [dbo].[PARENT_HEADS] ([PARENTHEAD_ID], [PARENTHEAD_TYPE], [PARENTHEAD_CODE], [PARENTHEAD_TITLE], [PARENTHEAD_TYPEII]) VALUES (54, N'A', N'040-020-000-000', N'DEBT SECURITIES ISSUED                                      ', N'B')
GO
INSERT [dbo].[PARENT_HEADS] ([PARENTHEAD_ID], [PARENTHEAD_TYPE], [PARENTHEAD_CODE], [PARENTHEAD_TITLE], [PARENTHEAD_TYPEII]) VALUES (55, N'A', N'040-030-000-000', N'LEASE OBLIGATIONS                                           ', N'B')
GO
INSERT [dbo].[PARENT_HEADS] ([PARENTHEAD_ID], [PARENTHEAD_TYPE], [PARENTHEAD_CODE], [PARENTHEAD_TITLE], [PARENTHEAD_TYPEII]) VALUES (56, N'A', N'040-040-000-000', N'DEFERRED TAX PAYABLES                                       ', N'B')
GO
INSERT [dbo].[PARENT_HEADS] ([PARENTHEAD_ID], [PARENTHEAD_TYPE], [PARENTHEAD_CODE], [PARENTHEAD_TITLE], [PARENTHEAD_TYPEII]) VALUES (57, N'A', N'040-050-000-000', N'UNCLAIMED DIVIDEND                                          ', N'B')
GO
INSERT [dbo].[PARENT_HEADS] ([PARENTHEAD_ID], [PARENTHEAD_TYPE], [PARENTHEAD_CODE], [PARENTHEAD_TITLE], [PARENTHEAD_TYPEII]) VALUES (58, N'A', N'040-060-000-000', N'UNSECURED LOANS                                             ', N'B')
GO
INSERT [dbo].[PARENT_HEADS] ([PARENTHEAD_ID], [PARENTHEAD_TYPE], [PARENTHEAD_CODE], [PARENTHEAD_TITLE], [PARENTHEAD_TYPEII]) VALUES (59, N'A', N'040-070-000-000', N'UNADJUSTED PROFIT AND LOSS                                  ', N'B')
GO
INSERT [dbo].[PARENT_HEADS] ([PARENTHEAD_ID], [PARENTHEAD_TYPE], [PARENTHEAD_CODE], [PARENTHEAD_TITLE], [PARENTHEAD_TYPEII]) VALUES (60, N'A', N'050-000-000-000', N'CAPITAL/ EQUITY                                             ', N'B')
GO
INSERT [dbo].[PARENT_HEADS] ([PARENTHEAD_ID], [PARENTHEAD_TYPE], [PARENTHEAD_CODE], [PARENTHEAD_TITLE], [PARENTHEAD_TYPEII]) VALUES (61, N'A', N'050-010-000-000', N'CAPITAL (SOLE PROPREITOR/PARTNER                            ', N'B')
GO
INSERT [dbo].[PARENT_HEADS] ([PARENTHEAD_ID], [PARENTHEAD_TYPE], [PARENTHEAD_CODE], [PARENTHEAD_TITLE], [PARENTHEAD_TYPEII]) VALUES (62, N'A', N'050-040-000-000', N'ISSUED AND SUBSCRIBED CAPITAL                               ', N'B')
GO
INSERT [dbo].[PARENT_HEADS] ([PARENTHEAD_ID], [PARENTHEAD_TYPE], [PARENTHEAD_CODE], [PARENTHEAD_TITLE], [PARENTHEAD_TYPEII]) VALUES (63, N'A', N'050-040-010-000', N'ORDINARY SHARES                                             ', N'B')
GO
INSERT [dbo].[PARENT_HEADS] ([PARENTHEAD_ID], [PARENTHEAD_TYPE], [PARENTHEAD_CODE], [PARENTHEAD_TITLE], [PARENTHEAD_TYPEII]) VALUES (64, N'A', N'050-040-020-000', N'SHARE PREMIUM                                               ', N'B')
GO
INSERT [dbo].[PARENT_HEADS] ([PARENTHEAD_ID], [PARENTHEAD_TYPE], [PARENTHEAD_CODE], [PARENTHEAD_TITLE], [PARENTHEAD_TYPEII]) VALUES (65, N'A', N'050-040-030-000', N'TREASURY SHARES                                             ', N'B')
GO
INSERT [dbo].[PARENT_HEADS] ([PARENTHEAD_ID], [PARENTHEAD_TYPE], [PARENTHEAD_CODE], [PARENTHEAD_TITLE], [PARENTHEAD_TYPEII]) VALUES (66, N'A', N'050-050-000-000', N'DIVIDEND PAYABLE                                            ', N'B')
GO
INSERT [dbo].[PARENT_HEADS] ([PARENTHEAD_ID], [PARENTHEAD_TYPE], [PARENTHEAD_CODE], [PARENTHEAD_TITLE], [PARENTHEAD_TYPEII]) VALUES (67, N'A', N'050-060-000-000', N'RETAINED EARNINGS                                           ', N'B')
GO
INSERT [dbo].[PARENT_HEADS] ([PARENTHEAD_ID], [PARENTHEAD_TYPE], [PARENTHEAD_CODE], [PARENTHEAD_TITLE], [PARENTHEAD_TYPEII]) VALUES (68, N'A', N'050-070-000-000', N'UNAPPROPRIATED PROFIT AND LOSS                              ', N'B')
GO
INSERT [dbo].[PARENT_HEADS] ([PARENTHEAD_ID], [PARENTHEAD_TYPE], [PARENTHEAD_CODE], [PARENTHEAD_TITLE], [PARENTHEAD_TYPEII]) VALUES (69, N'A', N'050-080-000-000', N'RESERVE FUNDS                                               ', N'B')
GO
INSERT [dbo].[PARENT_HEADS] ([PARENTHEAD_ID], [PARENTHEAD_TYPE], [PARENTHEAD_CODE], [PARENTHEAD_TITLE], [PARENTHEAD_TYPEII]) VALUES (70, N'A', N'060-000-000-000', N'GROSS PROFIT                                                ', N'I')
GO
INSERT [dbo].[PARENT_HEADS] ([PARENTHEAD_ID], [PARENTHEAD_TYPE], [PARENTHEAD_CODE], [PARENTHEAD_TITLE], [PARENTHEAD_TYPEII]) VALUES (71, N'A', N'060-010-000-000', N'SALES                                                       ', N'I')
GO
INSERT [dbo].[PARENT_HEADS] ([PARENTHEAD_ID], [PARENTHEAD_TYPE], [PARENTHEAD_CODE], [PARENTHEAD_TITLE], [PARENTHEAD_TYPEII]) VALUES (72, N'A', N'060-020-000-000', N'SALES DISCOUNT                                              ', N'I')
GO
INSERT [dbo].[PARENT_HEADS] ([PARENTHEAD_ID], [PARENTHEAD_TYPE], [PARENTHEAD_CODE], [PARENTHEAD_TITLE], [PARENTHEAD_TYPEII]) VALUES (73, N'A', N'060-030-000-000', N'SALES ALLOWANCES AND COMMISSION                             ', N'I')
GO
INSERT [dbo].[PARENT_HEADS] ([PARENTHEAD_ID], [PARENTHEAD_TYPE], [PARENTHEAD_CODE], [PARENTHEAD_TITLE], [PARENTHEAD_TYPEII]) VALUES (74, N'A', N'060-040-000-000', N'SALES RETURNS                                               ', N'I')
GO
INSERT [dbo].[PARENT_HEADS] ([PARENTHEAD_ID], [PARENTHEAD_TYPE], [PARENTHEAD_CODE], [PARENTHEAD_TITLE], [PARENTHEAD_TYPEII]) VALUES (75, N'A', N'060-050-000-000', N'COST OF GOODS SOLD                                          ', N'I')
GO
INSERT [dbo].[PARENT_HEADS] ([PARENTHEAD_ID], [PARENTHEAD_TYPE], [PARENTHEAD_CODE], [PARENTHEAD_TITLE], [PARENTHEAD_TYPEII]) VALUES (76, N'A', N'060-050-010-000', N'MATERIAL COST                                               ', N'I')
GO
INSERT [dbo].[PARENT_HEADS] ([PARENTHEAD_ID], [PARENTHEAD_TYPE], [PARENTHEAD_CODE], [PARENTHEAD_TITLE], [PARENTHEAD_TYPEII]) VALUES (77, N'A', N'060-050-010-010', N'OPENING STOCK                                               ', N'I')
GO
INSERT [dbo].[PARENT_HEADS] ([PARENTHEAD_ID], [PARENTHEAD_TYPE], [PARENTHEAD_CODE], [PARENTHEAD_TITLE], [PARENTHEAD_TYPEII]) VALUES (78, N'A', N'060-050-010-020', N'PURCHASES                                                   ', N'I')
GO
INSERT [dbo].[PARENT_HEADS] ([PARENTHEAD_ID], [PARENTHEAD_TYPE], [PARENTHEAD_CODE], [PARENTHEAD_TITLE], [PARENTHEAD_TYPEII]) VALUES (79, N'A', N'060-050-010-030', N'PURCHASES RETURNS                                           ', N'I')
GO
INSERT [dbo].[PARENT_HEADS] ([PARENTHEAD_ID], [PARENTHEAD_TYPE], [PARENTHEAD_CODE], [PARENTHEAD_TITLE], [PARENTHEAD_TYPEII]) VALUES (80, N'A', N'060-050-010-040', N'PURCHASED DISCOUNTS                                         ', N'I')
GO
INSERT [dbo].[PARENT_HEADS] ([PARENTHEAD_ID], [PARENTHEAD_TYPE], [PARENTHEAD_CODE], [PARENTHEAD_TITLE], [PARENTHEAD_TYPEII]) VALUES (81, N'A', N'060-050-010-050', N'PURCHASE ALLOWANCES AND COMISSION                           ', N'I')
GO
INSERT [dbo].[PARENT_HEADS] ([PARENTHEAD_ID], [PARENTHEAD_TYPE], [PARENTHEAD_CODE], [PARENTHEAD_TITLE], [PARENTHEAD_TYPEII]) VALUES (82, N'A', N'060-050-010-060', N'CLOSING STOCK                                               ', N'I')
GO
INSERT [dbo].[PARENT_HEADS] ([PARENTHEAD_ID], [PARENTHEAD_TYPE], [PARENTHEAD_CODE], [PARENTHEAD_TITLE], [PARENTHEAD_TYPEII]) VALUES (83, N'A', N'060-050-020-000', N'DIRECT LABOUR                                               ', N'I')
GO
INSERT [dbo].[PARENT_HEADS] ([PARENTHEAD_ID], [PARENTHEAD_TYPE], [PARENTHEAD_CODE], [PARENTHEAD_TITLE], [PARENTHEAD_TYPEII]) VALUES (84, N'A', N'060-050-030-000', N'OVERHEAD COSTS/ ABSORPTION EXPENDITURE                      ', N'I')
GO
INSERT [dbo].[PARENT_HEADS] ([PARENTHEAD_ID], [PARENTHEAD_TYPE], [PARENTHEAD_CODE], [PARENTHEAD_TITLE], [PARENTHEAD_TYPEII]) VALUES (85, N'A', N'070-000-000-000', N'NET PROFIT                                                  ', N'I')
GO
INSERT [dbo].[PARENT_HEADS] ([PARENTHEAD_ID], [PARENTHEAD_TYPE], [PARENTHEAD_CODE], [PARENTHEAD_TITLE], [PARENTHEAD_TYPEII]) VALUES (86, N'A', N'070-010-000-000', N'OPERATING EXPENDITURE (PERIOD COST)                         ', N'I')
GO
INSERT [dbo].[PARENT_HEADS] ([PARENTHEAD_ID], [PARENTHEAD_TYPE], [PARENTHEAD_CODE], [PARENTHEAD_TITLE], [PARENTHEAD_TYPEII]) VALUES (87, N'A', N'070-010-010-000', N'MANAGEMENT EXPENSES                                         ', N'I')
GO
INSERT [dbo].[PARENT_HEADS] ([PARENTHEAD_ID], [PARENTHEAD_TYPE], [PARENTHEAD_CODE], [PARENTHEAD_TITLE], [PARENTHEAD_TYPEII]) VALUES (88, N'A', N'070-010-020-000', N'ADMINISTRATIVE EXPENSES                                     ', N'I')
GO
INSERT [dbo].[PARENT_HEADS] ([PARENTHEAD_ID], [PARENTHEAD_TYPE], [PARENTHEAD_CODE], [PARENTHEAD_TITLE], [PARENTHEAD_TYPEII]) VALUES (89, N'A', N'070-010-030-000', N'SELLING EXPENSES                                            ', N'I')
GO
INSERT [dbo].[PARENT_HEADS] ([PARENTHEAD_ID], [PARENTHEAD_TYPE], [PARENTHEAD_CODE], [PARENTHEAD_TITLE], [PARENTHEAD_TYPEII]) VALUES (90, N'A', N'070-010-040-000', N'FINANCIAL EXPENSES                                          ', N'I')
GO
INSERT [dbo].[PARENT_HEADS] ([PARENTHEAD_ID], [PARENTHEAD_TYPE], [PARENTHEAD_CODE], [PARENTHEAD_TITLE], [PARENTHEAD_TYPEII]) VALUES (91, N'A', N'070-010-050-000', N'DEPRICIATION AND AMORTIZATION EXPENSES                      ', N'I')
GO
INSERT [dbo].[PARENT_HEADS] ([PARENTHEAD_ID], [PARENTHEAD_TYPE], [PARENTHEAD_CODE], [PARENTHEAD_TITLE], [PARENTHEAD_TYPEII]) VALUES (92, N'A', N'070-010-060-000', N'RESEARCH AND DEVELOPMENT EXPENSES                           ', N'I')
GO
INSERT [dbo].[PARENT_HEADS] ([PARENTHEAD_ID], [PARENTHEAD_TYPE], [PARENTHEAD_CODE], [PARENTHEAD_TITLE], [PARENTHEAD_TYPEII]) VALUES (93, N'A', N'070-020-000-000', N'NON OPERATING SECTION                                       ', N'I')
GO
INSERT [dbo].[PARENT_HEADS] ([PARENTHEAD_ID], [PARENTHEAD_TYPE], [PARENTHEAD_CODE], [PARENTHEAD_TITLE], [PARENTHEAD_TYPEII]) VALUES (94, N'A', N'070-020-010-000', N'RENT AND INTEREST INCOME                                    ', N'I')
GO
INSERT [dbo].[PARENT_HEADS] ([PARENTHEAD_ID], [PARENTHEAD_TYPE], [PARENTHEAD_CODE], [PARENTHEAD_TITLE], [PARENTHEAD_TYPEII]) VALUES (95, N'A', N'070-020-020-000', N'INCOME FROM PATENT OR GOODWILL                              ', N'I')
GO
INSERT [dbo].[PARENT_HEADS] ([PARENTHEAD_ID], [PARENTHEAD_TYPE], [PARENTHEAD_CODE], [PARENTHEAD_TITLE], [PARENTHEAD_TYPEII]) VALUES (96, N'A', N'070-020-030-000', N'GAIN FROM SALE OR SECURITIES                                ', N'I')
GO
INSERT [dbo].[PARENT_HEADS] ([PARENTHEAD_ID], [PARENTHEAD_TYPE], [PARENTHEAD_CODE], [PARENTHEAD_TITLE], [PARENTHEAD_TYPEII]) VALUES (97, N'A', N'070-020-040-000', N'GAIN FROM DISPOSAL OF FIXED ASSETS                          ', N'I')
GO
INSERT [dbo].[PARENT_HEADS] ([PARENTHEAD_ID], [PARENTHEAD_TYPE], [PARENTHEAD_CODE], [PARENTHEAD_TITLE], [PARENTHEAD_TYPEII]) VALUES (98, N'A', N'070-020-050-000', N'OTHER EXPENSES OR LOSSES                                    ', N'I')
GO
INSERT [dbo].[PARENT_HEADS] ([PARENTHEAD_ID], [PARENTHEAD_TYPE], [PARENTHEAD_CODE], [PARENTHEAD_TITLE], [PARENTHEAD_TYPEII]) VALUES (99, N'A', N'070-020-060-000', N'FINANCE COSTS                                               ', N'I')
GO
INSERT [dbo].[PARENT_HEADS] ([PARENTHEAD_ID], [PARENTHEAD_TYPE], [PARENTHEAD_CODE], [PARENTHEAD_TITLE], [PARENTHEAD_TYPEII]) VALUES (100, N'A', N'070-020-070-000', N'TAX EXPENSES                                                ', N'I')
GO
INSERT [dbo].[PARENT_HEADS] ([PARENTHEAD_ID], [PARENTHEAD_TYPE], [PARENTHEAD_CODE], [PARENTHEAD_TITLE], [PARENTHEAD_TYPEII]) VALUES (101, N'A', N'999-000-000-000', N'UNSPECIFIED PARENT CODE                                     ', NULL)
GO
INSERT [dbo].[PARENT_HEADS] ([PARENTHEAD_ID], [PARENTHEAD_TYPE], [PARENTHEAD_CODE], [PARENTHEAD_TITLE], [PARENTHEAD_TYPEII]) VALUES (102, N'I', N'010-000-000-000', N'RAW MATERIALS                                               ', N'B')
GO
INSERT [dbo].[PARENT_HEADS] ([PARENTHEAD_ID], [PARENTHEAD_TYPE], [PARENTHEAD_CODE], [PARENTHEAD_TITLE], [PARENTHEAD_TYPEII]) VALUES (103, N'I', N'010-010-000-000', N'CHEMICALS                                                   ', N'B')
GO
INSERT [dbo].[PARENT_HEADS] ([PARENTHEAD_ID], [PARENTHEAD_TYPE], [PARENTHEAD_CODE], [PARENTHEAD_TITLE], [PARENTHEAD_TYPEII]) VALUES (104, N'I', N'010-020-000-000', N'PETROLEUM PRODUCTS                                          ', N'B')
GO
INSERT [dbo].[PARENT_HEADS] ([PARENTHEAD_ID], [PARENTHEAD_TYPE], [PARENTHEAD_CODE], [PARENTHEAD_TITLE], [PARENTHEAD_TYPEII]) VALUES (105, N'I', N'010-030-000-000', N'IRON AND STEEL                                              ', N'B')
GO
INSERT [dbo].[PARENT_HEADS] ([PARENTHEAD_ID], [PARENTHEAD_TYPE], [PARENTHEAD_CODE], [PARENTHEAD_TITLE], [PARENTHEAD_TYPEII]) VALUES (106, N'I', N'010-040-000-000', N'PIPE AND FITTINGS                                           ', N'B')
GO
INSERT [dbo].[PARENT_HEADS] ([PARENTHEAD_ID], [PARENTHEAD_TYPE], [PARENTHEAD_CODE], [PARENTHEAD_TITLE], [PARENTHEAD_TYPEII]) VALUES (107, N'I', N'010-050-000-000', N'FABRICS AND CLOTHES                                         ', N'B')
GO
INSERT [dbo].[PARENT_HEADS] ([PARENTHEAD_ID], [PARENTHEAD_TYPE], [PARENTHEAD_CODE], [PARENTHEAD_TITLE], [PARENTHEAD_TYPEII]) VALUES (108, N'I', N'010-060-000-000', N'CONSUMABLE MATERIALS                                        ', N'B')
GO
INSERT [dbo].[PARENT_HEADS] ([PARENTHEAD_ID], [PARENTHEAD_TYPE], [PARENTHEAD_CODE], [PARENTHEAD_TITLE], [PARENTHEAD_TYPEII]) VALUES (109, N'I', N'010-070-000-000', N'AGRICULTURAL CROPS                                          ', N'B')
GO
INSERT [dbo].[PARENT_HEADS] ([PARENTHEAD_ID], [PARENTHEAD_TYPE], [PARENTHEAD_CODE], [PARENTHEAD_TITLE], [PARENTHEAD_TYPEII]) VALUES (110, N'I', N'010-080-000-000', N'PACKING MATERIALS                                           ', N'B')
GO
INSERT [dbo].[PARENT_HEADS] ([PARENTHEAD_ID], [PARENTHEAD_TYPE], [PARENTHEAD_CODE], [PARENTHEAD_TITLE], [PARENTHEAD_TYPEII]) VALUES (111, N'I', N'010-080-001-000', N'BARDANA / JUTE BAGS                                         ', N'B')
GO
INSERT [dbo].[PARENT_HEADS] ([PARENTHEAD_ID], [PARENTHEAD_TYPE], [PARENTHEAD_CODE], [PARENTHEAD_TITLE], [PARENTHEAD_TYPEII]) VALUES (112, N'I', N'010-080-002-000', N'COTTON / FIBRE BAGS                                         ', N'B')
GO
INSERT [dbo].[PARENT_HEADS] ([PARENTHEAD_ID], [PARENTHEAD_TYPE], [PARENTHEAD_CODE], [PARENTHEAD_TITLE], [PARENTHEAD_TYPEII]) VALUES (113, N'I', N'010-080-003-000', N'CARTONS AND BOXES                                           ', N'B')
GO
INSERT [dbo].[PARENT_HEADS] ([PARENTHEAD_ID], [PARENTHEAD_TYPE], [PARENTHEAD_CODE], [PARENTHEAD_TITLE], [PARENTHEAD_TYPEII]) VALUES (114, N'I', N'010-080-004-000', N'PAPERS AND ACCESSORIES                                      ', N'B')
GO
INSERT [dbo].[PARENT_HEADS] ([PARENTHEAD_ID], [PARENTHEAD_TYPE], [PARENTHEAD_CODE], [PARENTHEAD_TITLE], [PARENTHEAD_TYPEII]) VALUES (115, N'I', N'010-080-005-000', N'POLYTHEN BAGS                                               ', N'B')
GO
INSERT [dbo].[PARENT_HEADS] ([PARENTHEAD_ID], [PARENTHEAD_TYPE], [PARENTHEAD_CODE], [PARENTHEAD_TITLE], [PARENTHEAD_TYPEII]) VALUES (116, N'I', N'010-090-000-000', N'PLASTIC AND FIBRE MATERIALS                                 ', N'B')
GO
INSERT [dbo].[PARENT_HEADS] ([PARENTHEAD_ID], [PARENTHEAD_TYPE], [PARENTHEAD_CODE], [PARENTHEAD_TITLE], [PARENTHEAD_TYPEII]) VALUES (117, N'I', N'010-100-000-000', N'PETROLEUM PRODUCTS                                          ', N'B')
GO
INSERT [dbo].[PARENT_HEADS] ([PARENTHEAD_ID], [PARENTHEAD_TYPE], [PARENTHEAD_CODE], [PARENTHEAD_TITLE], [PARENTHEAD_TYPEII]) VALUES (118, N'I', N'020-000-000-000', N'FINISHED GOODS                                              ', N'B')
GO
INSERT [dbo].[PARENT_HEADS] ([PARENTHEAD_ID], [PARENTHEAD_TYPE], [PARENTHEAD_CODE], [PARENTHEAD_TITLE], [PARENTHEAD_TYPEII]) VALUES (119, N'I', N'020-010-000-000', N'READYMADE GARMENTS                                          ', N'B')
GO
INSERT [dbo].[PARENT_HEADS] ([PARENTHEAD_ID], [PARENTHEAD_TYPE], [PARENTHEAD_CODE], [PARENTHEAD_TITLE], [PARENTHEAD_TYPEII]) VALUES (120, N'I', N'020-020-000-000', N'PHARMACUTICALS / MEDICINES                                  ', N'B')
GO
INSERT [dbo].[PARENT_HEADS] ([PARENTHEAD_ID], [PARENTHEAD_TYPE], [PARENTHEAD_CODE], [PARENTHEAD_TITLE], [PARENTHEAD_TYPEII]) VALUES (121, N'I', N'020-030-000-000', N'AGRICULTURAL CROPS                                          ', N'B')
GO
INSERT [dbo].[PARENT_HEADS] ([PARENTHEAD_ID], [PARENTHEAD_TYPE], [PARENTHEAD_CODE], [PARENTHEAD_TITLE], [PARENTHEAD_TYPEII]) VALUES (122, N'I', N'020-040-000-000', N'ANIMALS CATTLE / SHEEP / OTHER                              ', N'B')
GO
INSERT [dbo].[PARENT_HEADS] ([PARENTHEAD_ID], [PARENTHEAD_TYPE], [PARENTHEAD_CODE], [PARENTHEAD_TITLE], [PARENTHEAD_TYPEII]) VALUES (123, N'I', N'020-050-000-000', N'FEEDS                                                       ', N'B')
GO
INSERT [dbo].[PARENT_HEADS] ([PARENTHEAD_ID], [PARENTHEAD_TYPE], [PARENTHEAD_CODE], [PARENTHEAD_TITLE], [PARENTHEAD_TYPEII]) VALUES (124, N'I', N'020-060-000-000', N'BISCUITS AND SWEETS                                         ', N'B')
GO
INSERT [dbo].[PARENT_HEADS] ([PARENTHEAD_ID], [PARENTHEAD_TYPE], [PARENTHEAD_CODE], [PARENTHEAD_TITLE], [PARENTHEAD_TYPEII]) VALUES (125, N'I', N'020-070-000-000', N'COSMETICS AND BEAUTY PRODUCTS                               ', N'B')
GO
INSERT [dbo].[PARENT_HEADS] ([PARENTHEAD_ID], [PARENTHEAD_TYPE], [PARENTHEAD_CODE], [PARENTHEAD_TITLE], [PARENTHEAD_TYPEII]) VALUES (126, N'I', N'020-080-000-000', N'SOAP AND TOILETERIES                                        ', N'B')
GO
INSERT [dbo].[PARENT_HEADS] ([PARENTHEAD_ID], [PARENTHEAD_TYPE], [PARENTHEAD_CODE], [PARENTHEAD_TITLE], [PARENTHEAD_TYPEII]) VALUES (127, N'I', N'020-090-000-000', N'PESTICIDES                                                  ', N'B')
GO
INSERT [dbo].[PARENT_HEADS] ([PARENTHEAD_ID], [PARENTHEAD_TYPE], [PARENTHEAD_CODE], [PARENTHEAD_TITLE], [PARENTHEAD_TYPEII]) VALUES (128, N'I', N'020-100-000-000', N'FRUITS AND VEGETABLES                                       ', N'B')
GO
INSERT [dbo].[PARENT_HEADS] ([PARENTHEAD_ID], [PARENTHEAD_TYPE], [PARENTHEAD_CODE], [PARENTHEAD_TITLE], [PARENTHEAD_TYPEII]) VALUES (129, N'I', N'020-110-000-000', N'GRAINS AND LENTILS                                          ', N'B')
GO
INSERT [dbo].[PARENT_HEADS] ([PARENTHEAD_ID], [PARENTHEAD_TYPE], [PARENTHEAD_CODE], [PARENTHEAD_TITLE], [PARENTHEAD_TYPEII]) VALUES (130, N'I', N'020-120-000-000', N'CONSTRUCTION MATERIALS                                      ', N'B')
GO
INSERT [dbo].[PARENT_HEADS] ([PARENTHEAD_ID], [PARENTHEAD_TYPE], [PARENTHEAD_CODE], [PARENTHEAD_TITLE], [PARENTHEAD_TYPEII]) VALUES (131, N'I', N'020-130-000-000', N'Computer Hardware                                           ', N'B')
GO
ALTER TABLE [dbo].[ACC_TRANS_HEADER]  WITH CHECK ADD  CONSTRAINT [FK_ACC_TRANS_HEADER_BOOKProperties] FOREIGN KEY([BOOKID])
REFERENCES [dbo].[BOOKProperties] ([BOOK_ID])
GO
ALTER TABLE [dbo].[ACC_TRANS_HEADER] CHECK CONSTRAINT [FK_ACC_TRANS_HEADER_BOOKProperties]
GO
ALTER TABLE [dbo].[ADDRESS_CARD]  WITH CHECK ADD  CONSTRAINT [FK_ADDRESS_CARD_ACCOUNT_HEADS] FOREIGN KEY([ACCHEAD_ID])
REFERENCES [dbo].[ACCOUNT_HEADS] ([ACCHEAD_ID])
GO
ALTER TABLE [dbo].[ADDRESS_CARD] CHECK CONSTRAINT [FK_ADDRESS_CARD_ACCOUNT_HEADS]
GO
ALTER TABLE [dbo].[DEPRICIATION_CARD]  WITH CHECK ADD  CONSTRAINT [FK_DEPRICIATION_CARD_ACCOUNT_HEADS] FOREIGN KEY([ACCHEAD_ID])
REFERENCES [dbo].[ACCOUNT_HEADS] ([ACCHEAD_ID])
GO
ALTER TABLE [dbo].[DEPRICIATION_CARD] CHECK CONSTRAINT [FK_DEPRICIATION_CARD_ACCOUNT_HEADS]
GO
ALTER TABLE [dbo].[DEPRICIATION_YEARLYRATES]  WITH CHECK ADD  CONSTRAINT [FK_DEPRICIATION_YEARLYRATES_DEPRICIATION_CARD] FOREIGN KEY([DEPCARD_ID])
REFERENCES [dbo].[DEPRICIATION_CARD] ([DEPCARD_ID])
GO
ALTER TABLE [dbo].[DEPRICIATION_YEARLYRATES] CHECK CONSTRAINT [FK_DEPRICIATION_YEARLYRATES_DEPRICIATION_CARD]
GO
ALTER TABLE [dbo].[TERMS_AND_CONDITIONS]  WITH CHECK ADD  CONSTRAINT [FK_TERMS_AND_CONDITIONS_TERMS_AND_CONDITIONS] FOREIGN KEY([TnC_ID])
REFERENCES [dbo].[TERMS_AND_CONDITIONS] ([TnC_ID])
GO
ALTER TABLE [dbo].[TERMS_AND_CONDITIONS] CHECK CONSTRAINT [FK_TERMS_AND_CONDITIONS_TERMS_AND_CONDITIONS]
GO
/****** Object:  StoredProcedure [dbo].[AccAtt]    Script Date: 4/5/2021 11:17:56 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROC [dbo].[AccAtt] @Code nvarchar(15)
AS
SELECT AH.ACCHEAD_NAME, AA.ACCATTRIBUTE_AREA_ENGINENO, AA.ACCATTRIBUTE_SIZE_CHASS FROM ACCOUNT_HEADS AS AH
INNER JOIN PARENT_HEADS ON AH.ACCPARENTHEAD_ID = PARENT_HEADS.PARENTHEAD_ID
INNER JOIN ACCOUNT_ATTRIBUTES AS AA ON AH.ACCHEAD_ID = AA.ACCHEAD_ID
WHERE PARENT_HEADS.PARENTHEAD_CODE = @Code
GO
/****** Object:  StoredProcedure [dbo].[AccAtt_DepCar_DepYearly]    Script Date: 4/5/2021 11:17:56 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROC [dbo].[AccAtt_DepCar_DepYearly] @Code nvarchar(15)
AS
SELECT AH.ACCHEAD_NAME, AA.ACCATTRIBUTE_AREA_ENGINENO, AA.ACCATTRIBUTE_SIZE_CHASS, DC.DEP_LIFE, DC.DEP_METHOD, DC.DEP_PURCHASEDATE, DC.DEP_RATE, DC.DEP_YEARLYRATE, DC.ACCATTRIBUTE_DEP_SALVAGE,
DY.YEARNO, DY.YEARRATE FROM ACCOUNT_HEADS AS AH
INNER JOIN PARENT_HEADS ON AH.ACCPARENTHEAD_ID = PARENT_HEADS.PARENTHEAD_ID
INNER JOIN ACCOUNT_ATTRIBUTES AS AA ON AH.ACCHEAD_ID = AA.ACCHEAD_ID
INNER JOIN DEPRICIATION_CARD AS DC ON DC.ACCHEAD_ID =  AH.ACCHEAD_ID
INNER JOIN DEPRICIATION_YEARLYRATES AS DY ON DY.DEPCARD_ID = DC.DEPCARD_ID
WHERE PARENT_HEADS.PARENTHEAD_CODE = @Code
GO
/****** Object:  StoredProcedure [dbo].[AccountHeadGivenParentHead]    Script Date: 4/5/2021 11:17:56 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROC [dbo].[AccountHeadGivenParentHead] @Code nvarchar(15)
AS
Select ACCOUNT_HEADS.ACCHEAD_ID, ACCOUNT_HEADS.ACCHEAD_NAME from ACCOUNT_HEADS 
INNER JOIN PARENT_HEADS
ON ACCOUNT_HEADS.ACCPARENTHEAD_ID = PARENT_HEADS.PARENTHEAD_ID
WHERE PARENT_HEADS.PARENTHEAD_CODE = @Code;
GO
/****** Object:  StoredProcedure [dbo].[AddCard]    Script Date: 4/5/2021 11:17:56 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROC [dbo].[AddCard] @Code nvarchar(15)
AS
SELECT AH.ACCHEAD_NAME, AC.ADDRESS_LINE1, AC.ADDRESS_LINE2, AC.ADDRESS_LINE3, AC.CITY, AC.COUNTRY, AC.CR_LIMIT_AMOUNT, AC.CR_LIMIT_DAYS FROM ACCOUNT_HEADS AS AH
INNER JOIN PARENT_HEADS ON AH.ACCPARENTHEAD_ID = PARENT_HEADS.PARENTHEAD_ID
INNER JOIN ADDRESS_CARD AS AC ON AH.ACCHEAD_ID = AC.ACCHEAD_ID
WHERE PARENT_HEADS.PARENTHEAD_CODE = @Code
GO
/****** Object:  StoredProcedure [dbo].[Count_Heads]    Script Date: 4/5/2021 11:17:56 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[Count_Heads] @Code nvarchar(15), @TypeACCINV nvarchar(1), @TypeBALINC nvarchar(1)
AS
SELECT COUNT(PARENTHEAD_CODE)
FROM PARENT_HEADS
WHERE PARENTHEAD_CODE LIKE @Code AND PARENTHEAD_TYPE = @TypeACCINV AND PARENTHEAD_TYPEII = @TypeBALINC 
GO
/****** Object:  StoredProcedure [dbo].[DepCard_DepYearly]    Script Date: 4/5/2021 11:17:56 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROC [dbo].[DepCard_DepYearly] @Code nvarchar(15)
AS
SELECT ACCOUNT_HEADS.ACCHEAD_NAME, DC.DEP_LIFE, DC.DEP_METHOD, DC.DEP_PURCHASEDATE, DC.DEP_RATE, DC.DEP_YEARLYRATE, DC.ACCATTRIBUTE_DEP_SALVAGE,
DY.YEARNO, DY.YEARRATE FROM ACCOUNT_HEADS
INNER JOIN PARENT_HEADS ON ACCOUNT_HEADS.ACCPARENTHEAD_ID = PARENT_HEADS.PARENTHEAD_ID
INNER JOIN DEPRICIATION_CARD AS DC ON DC.ACCHEAD_ID =  ACCOUNT_HEADS.ACCHEAD_ID
INNER JOIN DEPRICIATION_YEARLYRATES AS DY ON DY.DEPCARD_ID = DC.DEPCARD_ID
WHERE PARENT_HEADS.PARENTHEAD_CODE = @Code
GO
/****** Object:  StoredProcedure [dbo].[Heads_CodeTitle]    Script Date: 4/5/2021 11:17:56 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[Heads_CodeTitle] @Code nvarchar(15), @TypeACCINV nvarchar(1), @TypeBALINC nvarchar(1)
AS
SELECT PARENTHEAD_CODE, PARENTHEAD_TITLE
FROM PARENT_HEADS
WHERE PARENTHEAD_CODE LIKE @Code AND PARENTHEAD_TYPE = @TypeACCINV AND PARENTHEAD_TYPEII = @TypeBALINC
ORDER BY PARENTHEAD_CODE
GO
/****** Object:  StoredProcedure [dbo].[InventoryHeadGivenParentHead]    Script Date: 4/5/2021 11:17:56 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE PROC [dbo].[InventoryHeadGivenParentHead] @Code nvarchar(15)
AS
Select INVENTORY_HEADS.INVHEAD_ID, INVENTORY_HEADS.INVHEAD_NAME from INVENTORY_HEADS 
INNER JOIN PARENT_HEADS
ON INVENTORY_HEADS.INVPARENTHEAD_ID = PARENT_HEADS.PARENTHEAD_ID
WHERE PARENT_HEADS.PARENTHEAD_CODE = @Code;

GO
/****** Object:  StoredProcedure [dbo].[RetrieveAccHeads]    Script Date: 4/5/2021 11:17:56 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROC [dbo].[RetrieveAccHeads]
AS
SELECT RIGHT('0000000' + CONVERT(VARCHAR(7), AH.ACCHEAD_ID), 7) AS 'Account Code',
PH.PARENTHEAD_CODE AS 'Parent Code', PH.PARENTHEAD_TITLE AS 'Parent Title', AH.ACCHEAD_NAME AS 'Account Title', AH.ADDCARD_CHOICE AS 'Address',
AH.ATTRIBUTE_CHOICE AS 'Attributes', AH.DEPCARD_CHOICE AS 'Depriciation', AH.PICTURE_CHOICE AS 'Depriciation Yearly Rate'
FROM ACCOUNT_HEADS AS AH 
INNER JOIN PARENT_HEADS AS PH
ON AH.ACCPARENTHEAD_ID=PH.PARENTHEAD_ID
GO
/****** Object:  StoredProcedure [dbo].[RetrieveINVHeadscode]    Script Date: 4/5/2021 11:17:56 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROC [dbo].[RetrieveINVHeadscode] 
AS
SELECT RIGHT('0000000' + CONVERT(VARCHAR(7), IH.INVHEAD_ID), 7) AS 'INVENTORY Code',
PH.PARENTHEAD_CODE AS 'Parent Code', PH.PARENTHEAD_TITLE AS 'Parent Title', IH.INVHEAD_NAME AS 'INVENTORY Title',IH.INV_CODE_PARTNO 
AS 'INVENTORY CODE PART NO',IH.INV_SPECIFICATION_CHOICE AS 'INVENTORY SPECIFICATION',IH.INV_PICTURE_CHOICE AS 'INVENTORY PICTURE CHOICE',
IH.INVHEAD_ID,IH.INVHEAD_NAME,ISA.INV_SPECIFICATIONS, IA.STOCK_UNIT,  IA.PACKING_UNIT,  IA.LOOSE_UNIT,  IA.RATE_PER_LOOSE_UNIT,  IA.RATE_PER_STOCK_UNIT,  IA.RATE_PER_PACKING_UNIT,  IA.RATE_PRICE_LOOSE_UNIT,
 IA.RATE_PRICE_STOCK_UNIT,  IA.RATE_PRICE_PACKING_UNIT, IA.BALANCE_LOOSE_UNIT,  IA.BALANCE_STOCK_UNIT,
IA.BALANCE_PACKING_UNIT, IA.COST_LOOSE_UNIT, IA.COST_STOCK_UNIT, IA.COST_PACKING_UNIT
FROM INVENTORY_HEADS AS IH 
INNER JOIN PARENT_HEADS AS PH
ON IH.INVPARENTHEAD_ID=PH.PARENTHEAD_ID
INNER JOIN INVENTORY_ATTRIBUTES AS IA
ON IH.INVHEAD_ID=IA.INVHEAD_ID
INNER JOIN INVENTORY_SPECIFICATIONS AS ISA
ON ISA.INVHEAD_ID=IA.INVHEAD_ID

GO
/****** Object:  StoredProcedure [dbo].[RetrieveINVHeadscode_loose]    Script Date: 4/5/2021 11:17:56 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROC [dbo].[RetrieveINVHeadscode_loose] @Code nvarchar(15)
AS
SELECT RIGHT('0000000' + CONVERT(VARCHAR(7), IH.INVHEAD_ID), 7) AS 'INVENTORY Code',
PH.PARENTHEAD_CODE AS 'Parent Code', PH.PARENTHEAD_TITLE AS 'Parent Title', IH.INVHEAD_NAME AS 'INVENTORY Title',IH.INV_CODE_PARTNO 
AS 'INVENTORY CODE PART NO',IH.INV_SPECIFICATION_CHOICE AS 'INVENTORY SPECIFICATION',IH.INV_PICTURE_CHOICE AS 'INVENTORY PICTURE CHOICE',
IH.INVHEAD_ID,IH.INVHEAD_NAME,ISA.INV_SPECIFICATIONS, IA.LOOSE_UNIT,  IA.RATE_PER_LOOSE_UNIT,
 IA.RATE_PER_LOOSE_UNIT,  IA.BALANCE_LOOSE_UNIT
, IA.COST_LOOSE_UNIT
FROM INVENTORY_HEADS AS IH 
INNER JOIN PARENT_HEADS AS PH
ON IH.INVHEAD_ID=PH.PARENTHEAD_ID
INNER JOIN INVENTORY_ATTRIBUTES AS IA
ON IH.INVHEAD_ID=IA.INVHEAD_ID
INNER JOIN INVENTORY_SPECIFICATIONS AS ISA
ON ISA.INVHEAD_ID=IA.INVHEAD_ID
where ph.PARENTHEAD_CODE = @Code
GO
/****** Object:  StoredProcedure [dbo].[RetrieveINVHeadscode_looset]    Script Date: 4/5/2021 11:17:56 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROC [dbo].[RetrieveINVHeadscode_looset] @title nvarchar(255)
AS
SELECT RIGHT('0000000' + CONVERT(VARCHAR(7), IH.INVHEAD_ID), 7) AS 'INVENTORY Code',
PH.PARENTHEAD_CODE AS 'Parent Code', PH.PARENTHEAD_TITLE AS 'Parent Title', IH.INVHEAD_NAME AS 'INVENTORY Title',IH.INV_CODE_PARTNO 
AS 'INVENTORY CODE PART NO',IH.INV_SPECIFICATION_CHOICE AS 'INVENTORY SPECIFICATION',IH.INV_PICTURE_CHOICE AS 'INVENTORY PICTURE CHOICE',
IH.INVHEAD_ID,IH.INVHEAD_NAME,ISA.INV_SPECIFICATIONS, IA.LOOSE_UNIT,  IA.RATE_PER_LOOSE_UNIT,
 IA.RATE_PER_LOOSE_UNIT,  IA.BALANCE_LOOSE_UNIT
, IA.COST_LOOSE_UNIT
FROM INVENTORY_HEADS AS IH 
INNER JOIN PARENT_HEADS AS PH
ON IH.INVPARENTHEAD_ID=PH.PARENTHEAD_ID
INNER JOIN INVENTORY_ATTRIBUTES AS IA
ON IH.INVHEAD_ID=IA.INVHEAD_ID
INNER JOIN INVENTORY_SPECIFICATIONS AS ISA
ON ISA.INVHEAD_ID=IA.INVHEAD_ID
where ph.PARENTHEAD_TITLE = @title
GO
/****** Object:  StoredProcedure [dbo].[RetrieveINVHeadscode_packing]    Script Date: 4/5/2021 11:17:56 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROC [dbo].[RetrieveINVHeadscode_packing] @Code nvarchar(15)
AS
SELECT RIGHT('0000000' + CONVERT(VARCHAR(7), IH.INVHEAD_ID), 7) AS 'INVENTORY Code',
PH.PARENTHEAD_CODE AS 'Parent Code', PH.PARENTHEAD_TITLE AS 'Parent Title', IH.INVHEAD_NAME AS 'INVENTORY Title',IH.INV_CODE_PARTNO 
AS 'INVENTORY CODE PART NO',IH.INV_SPECIFICATION_CHOICE AS 'INVENTORY SPECIFICATION',IH.INV_PICTURE_CHOICE AS 'INVENTORY PICTURE CHOICE',
IH.INVHEAD_ID,IH.INVHEAD_NAME,ISA.INV_SPECIFICATIONS, IA.LOOSE_UNIT,  IA.RATE_PER_LOOSE_UNIT,
 IA.RATE_PRICE_LOOSE_UNIT,  IA.BALANCE_LOOSE_UNIT
FROM INVENTORY_HEADS AS IH 
INNER JOIN PARENT_HEADS AS PH
ON IH.INVPARENTHEAD_ID=PH.PARENTHEAD_ID
INNER JOIN INVENTORY_ATTRIBUTES AS IA
ON IH.INVHEAD_ID=IA.INVHEAD_ID
INNER JOIN INVENTORY_SPECIFICATIONS AS ISA
ON ISA.INVHEAD_ID=IA.INVHEAD_ID
where ph.PARENTHEAD_CODE = @Code
GO
/****** Object:  StoredProcedure [dbo].[RetrieveINVHeadscode_packingloose]    Script Date: 4/5/2021 11:17:56 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE PROC [dbo].[RetrieveINVHeadscode_packingloose] @Code nvarchar(15)
AS
SELECT RIGHT('0000000' + CONVERT(VARCHAR(7), IH.INVHEAD_ID), 7) AS 'INVENTORY Code',
PH.PARENTHEAD_CODE AS 'Parent Code', PH.PARENTHEAD_TITLE AS 'Parent Title', IH.INVHEAD_NAME AS 'INVENTORY Title',IH.INV_CODE_PARTNO 
AS 'INVENTORY CODE PART NO',IH.INV_SPECIFICATION_CHOICE AS 'INVENTORY SPECIFICATION',IH.INV_PICTURE_CHOICE AS 'INVENTORY PICTURE CHOICE',
ISA.INV_SPECIFICATIONS, 
		IA.PACKING_UNIT, IA.LOOSE_UNIT, IA.RATE_PER_LOOSE_UNIT, IA.RATE_PER_PACKING_UNIT, IA.RATE_PRICE_LOOSE_UNIT, IA.RATE_PRICE_PACKING_UNIT, 
		IA.BALANCE_LOOSE_UNIT, IA.BALANCE_PACKING_UNIT, IA.COST_LOOSE_UNIT, IA.COST_PACKING_UNIT
FROM INVENTORY_HEADS AS IH 
INNER JOIN PARENT_HEADS AS PH
ON IH.INVPARENTHEAD_ID=PH.PARENTHEAD_ID
INNER JOIN INVENTORY_ATTRIBUTES AS IA
ON IH.INVHEAD_ID=IA.INVHEAD_ID
INNER JOIN INVENTORY_SPECIFICATIONS AS ISA
ON ISA.INVHEAD_ID=IA.INVHEAD_ID
where ph.PARENTHEAD_CODE = @Code
GO
/****** Object:  StoredProcedure [dbo].[RetrieveINVHeadscode_packinglooset]    Script Date: 4/5/2021 11:17:56 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE PROC [dbo].[RetrieveINVHeadscode_packinglooset] @title nvarchar(255)
AS
SELECT RIGHT('0000000' + CONVERT(VARCHAR(7), IH.INVHEAD_ID), 7) AS 'INVENTORY Code',
PH.PARENTHEAD_CODE AS 'Parent Code', PH.PARENTHEAD_TITLE AS 'Parent Title', IH.INVHEAD_NAME AS 'INVENTORY Title',IH.INV_CODE_PARTNO 
AS 'INVENTORY CODE PART NO',IH.INV_SPECIFICATION_CHOICE AS 'INVENTORY SPECIFICATION',IH.INV_PICTURE_CHOICE AS 'INVENTORY PICTURE CHOICE',
ISA.INV_SPECIFICATIONS, 
		IA.PACKING_UNIT, IA.LOOSE_UNIT, IA.RATE_PER_LOOSE_UNIT, IA.RATE_PER_PACKING_UNIT, IA.RATE_PRICE_LOOSE_UNIT, IA.RATE_PRICE_PACKING_UNIT, 
		IA.BALANCE_LOOSE_UNIT, IA.BALANCE_PACKING_UNIT, IA.COST_LOOSE_UNIT, IA.COST_PACKING_UNIT
FROM INVENTORY_HEADS AS IH 
INNER JOIN PARENT_HEADS AS PH
ON IH.INVPARENTHEAD_ID=PH.PARENTHEAD_ID
INNER JOIN INVENTORY_ATTRIBUTES AS IA
ON IH.INVHEAD_ID=IA.INVHEAD_ID
INNER JOIN INVENTORY_SPECIFICATIONS AS ISA
ON ISA.INVHEAD_ID=IA.INVHEAD_ID
where ph.PARENTHEAD_TITLE = @title
GO
/****** Object:  StoredProcedure [dbo].[RetrieveINVHeadscode_packingt]    Script Date: 4/5/2021 11:17:56 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROC [dbo].[RetrieveINVHeadscode_packingt] @title nvarchar(255)
AS
SELECT RIGHT('0000000' + CONVERT(VARCHAR(7), IH.INVHEAD_ID), 7) AS 'INVENTORY Code',
PH.PARENTHEAD_CODE AS 'Parent Code', PH.PARENTHEAD_TITLE AS 'Parent Title', IH.INVHEAD_NAME AS 'INVENTORY Title',IH.INV_CODE_PARTNO 
AS 'INVENTORY CODE PART NO',IH.INV_SPECIFICATION_CHOICE AS 'INVENTORY SPECIFICATION',IH.INV_PICTURE_CHOICE AS 'INVENTORY PICTURE CHOICE',
IH.INVHEAD_ID,IH.INVHEAD_NAME,ISA.INV_SPECIFICATIONS, IA.LOOSE_UNIT,  IA.RATE_PER_LOOSE_UNIT,
 IA.RATE_PRICE_LOOSE_UNIT,  IA.BALANCE_LOOSE_UNIT
FROM INVENTORY_HEADS AS IH 
INNER JOIN PARENT_HEADS AS PH
ON IH.INVPARENTHEAD_ID=PH.PARENTHEAD_ID
INNER JOIN INVENTORY_ATTRIBUTES AS IA
ON IH.INVHEAD_ID=IA.INVHEAD_ID
INNER JOIN INVENTORY_SPECIFICATIONS AS ISA
ON ISA.INVHEAD_ID=IA.INVHEAD_ID
where ph.PARENTHEAD_TITLE = @title
GO
/****** Object:  StoredProcedure [dbo].[RetrieveINVHeadscode_stock]    Script Date: 4/5/2021 11:17:56 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE PROC [dbo].[RetrieveINVHeadscode_stock] @Code nvarchar(15)
AS
SELECT RIGHT('0000000' + CONVERT(VARCHAR(7), IH.INVHEAD_ID), 7) AS 'INVENTORY Code',
PH.PARENTHEAD_CODE AS 'Parent Code', PH.PARENTHEAD_TITLE AS 'Parent Title', IH.INVHEAD_NAME AS 'INVENTORY Title',IH.INV_CODE_PARTNO 
AS 'INVENTORY CODE PART NO',IH.INV_SPECIFICATION_CHOICE AS 'INVENTORY SPECIFICATION',IH.INV_PICTURE_CHOICE AS 'INVENTORY PICTURE CHOICE',
IH.INVHEAD_ID,IH.INVHEAD_NAME,ISA.INV_SPECIFICATIONS, IA.STOCK_UNIT,  IA.RATE_PER_STOCK_UNIT,
 IA.RATE_PRICE_STOCK_UNIT,  IA.BALANCE_STOCK_UNIT
, IA.COST_STOCK_UNIT
FROM INVENTORY_HEADS AS IH 
INNER JOIN PARENT_HEADS AS PH
ON IH.INVPARENTHEAD_ID=PH.PARENTHEAD_ID
INNER JOIN INVENTORY_ATTRIBUTES AS IA
ON IH.INVHEAD_ID=IA.INVHEAD_ID
INNER JOIN INVENTORY_SPECIFICATIONS AS ISA
ON ISA.INVHEAD_ID=IA.INVHEAD_ID
where ph.PARENTHEAD_CODE = @Code
GO
/****** Object:  StoredProcedure [dbo].[RetrieveINVHeadscode_stockloose]    Script Date: 4/5/2021 11:17:56 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROC [dbo].[RetrieveINVHeadscode_stockloose] @Code nvarchar(15)
AS
SELECT RIGHT('0000000' + CONVERT(VARCHAR(7), IH.INVHEAD_ID), 7) AS 'INVENTORY Code',
PH.PARENTHEAD_CODE AS 'Parent Code', PH.PARENTHEAD_TITLE AS 'Parent Title', IH.INVHEAD_NAME AS 'INVENTORY Title',IH.INV_CODE_PARTNO 
AS 'INVENTORY CODE PART NO',IH.INV_SPECIFICATION_CHOICE AS 'INVENTORY SPECIFICATION',IH.INV_PICTURE_CHOICE AS 'INVENTORY PICTURE CHOICE',
ISA.INV_SPECIFICATIONS, 
IA.STOCK_UNIT, IA.LOOSE_UNIT, IA.RATE_PER_LOOSE_UNIT, IA.RATE_PER_STOCK_UNIT, IA.RATE_PRICE_LOOSE_UNIT, IA.RATE_PRICE_STOCK_UNIT,
IA.BALANCE_LOOSE_UNIT,	IA.BALANCE_STOCK_UNIT, IA.COST_LOOSE_UNIT, IA.COST_STOCK_UNIT
FROM INVENTORY_HEADS AS IH 
INNER JOIN PARENT_HEADS AS PH
ON IH.INVPARENTHEAD_ID=PH.PARENTHEAD_ID
INNER JOIN INVENTORY_ATTRIBUTES AS IA
ON IH.INVHEAD_ID=IA.INVHEAD_ID
INNER JOIN INVENTORY_SPECIFICATIONS AS ISA
ON ISA.INVHEAD_ID=IA.INVHEAD_ID
where ph.PARENTHEAD_CODE = @Code
GO
/****** Object:  StoredProcedure [dbo].[RetrieveINVHeadscode_stocklooset]    Script Date: 4/5/2021 11:17:56 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROC [dbo].[RetrieveINVHeadscode_stocklooset] @title nvarchar(255)
AS
SELECT RIGHT('0000000' + CONVERT(VARCHAR(7), IH.INVHEAD_ID), 7) AS 'INVENTORY Code',
PH.PARENTHEAD_CODE AS 'Parent Code', PH.PARENTHEAD_TITLE AS 'Parent Title', IH.INVHEAD_NAME AS 'INVENTORY Title',IH.INV_CODE_PARTNO 
AS 'INVENTORY CODE PART NO',IH.INV_SPECIFICATION_CHOICE AS 'INVENTORY SPECIFICATION',IH.INV_PICTURE_CHOICE AS 'INVENTORY PICTURE CHOICE',
ISA.INV_SPECIFICATIONS, 
IA.STOCK_UNIT, IA.LOOSE_UNIT, IA.RATE_PER_LOOSE_UNIT, IA.RATE_PER_STOCK_UNIT, IA.RATE_PRICE_LOOSE_UNIT, IA.RATE_PRICE_STOCK_UNIT,
IA.BALANCE_LOOSE_UNIT,	IA.BALANCE_STOCK_UNIT, IA.COST_LOOSE_UNIT, IA.COST_STOCK_UNIT
FROM INVENTORY_HEADS AS IH 
INNER JOIN PARENT_HEADS AS PH
ON IH.INVPARENTHEAD_ID=PH.PARENTHEAD_ID
INNER JOIN INVENTORY_ATTRIBUTES AS IA
ON IH.INVHEAD_ID=IA.INVHEAD_ID
INNER JOIN INVENTORY_SPECIFICATIONS AS ISA
ON ISA.INVHEAD_ID=IA.INVHEAD_ID
where ph.PARENTHEAD_TITLE = @title
GO
/****** Object:  StoredProcedure [dbo].[RetrieveINVHeadscode_stockpacking]    Script Date: 4/5/2021 11:17:56 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE PROC [dbo].[RetrieveINVHeadscode_stockpacking] @Code nvarchar(15)
AS
SELECT RIGHT('0000000' + CONVERT(VARCHAR(7), IH.INVHEAD_ID), 7) AS 'INVENTORY Code',
PH.PARENTHEAD_CODE AS 'Parent Code', PH.PARENTHEAD_TITLE AS 'Parent Title', IH.INVHEAD_NAME AS 'INVENTORY Title',IH.INV_CODE_PARTNO 
AS 'INVENTORY CODE PART NO',IH.INV_SPECIFICATION_CHOICE AS 'INVENTORY SPECIFICATION',IH.INV_PICTURE_CHOICE AS 'INVENTORY PICTURE CHOICE',
ISA.INV_SPECIFICATIONS, 
IA.STOCK_UNIT, IA.PACKING_UNIT, IA.RATE_PER_STOCK_UNIT, IA.RATE_PER_PACKING_UNIT, IA.RATE_PRICE_STOCK_UNIT, IA.RATE_PRICE_PACKING_UNIT,
IA.BALANCE_STOCK_UNIT, IA.BALANCE_PACKING_UNIT, IA.COST_STOCK_UNIT, IA.COST_PACKING_UNIT
FROM INVENTORY_HEADS AS IH 
INNER JOIN PARENT_HEADS AS PH
ON IH.INVPARENTHEAD_ID=PH.PARENTHEAD_ID
INNER JOIN INVENTORY_ATTRIBUTES AS IA
ON IH.INVHEAD_ID=IA.INVHEAD_ID
INNER JOIN INVENTORY_SPECIFICATIONS AS ISA
ON ISA.INVHEAD_ID=IA.INVHEAD_ID
where ph.PARENTHEAD_CODE = @Code
GO
/****** Object:  StoredProcedure [dbo].[RetrieveINVHeadscode_stockpackingt]    Script Date: 4/5/2021 11:17:56 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROC [dbo].[RetrieveINVHeadscode_stockpackingt] @title nvarchar(255)
AS
SELECT RIGHT('0000000' + CONVERT(VARCHAR(7), IH.INVHEAD_ID), 7) AS 'INVENTORY Code',
PH.PARENTHEAD_CODE AS 'Parent Code', PH.PARENTHEAD_TITLE AS 'Parent Title', IH.INVHEAD_NAME AS 'INVENTORY Title',IH.INV_CODE_PARTNO 
AS 'INVENTORY CODE PART NO',IH.INV_SPECIFICATION_CHOICE AS 'INVENTORY SPECIFICATION',IH.INV_PICTURE_CHOICE AS 'INVENTORY PICTURE CHOICE',
ISA.INV_SPECIFICATIONS, 
IA.STOCK_UNIT, IA.PACKING_UNIT, IA.RATE_PER_STOCK_UNIT, IA.RATE_PER_PACKING_UNIT, IA.RATE_PRICE_STOCK_UNIT, IA.RATE_PRICE_PACKING_UNIT,
IA.BALANCE_STOCK_UNIT, IA.BALANCE_PACKING_UNIT, IA.COST_STOCK_UNIT, IA.COST_PACKING_UNIT
FROM INVENTORY_HEADS AS IH 
INNER JOIN PARENT_HEADS AS PH
ON IH.INVPARENTHEAD_ID=PH.PARENTHEAD_ID
INNER JOIN INVENTORY_ATTRIBUTES AS IA
ON IH.INVHEAD_ID=IA.INVHEAD_ID
INNER JOIN INVENTORY_SPECIFICATIONS AS ISA
ON ISA.INVHEAD_ID=IA.INVHEAD_ID
where ph.PARENTHEAD_TITLE = @title
GO
/****** Object:  StoredProcedure [dbo].[RetrieveINVHeadscode_stockt]    Script Date: 4/5/2021 11:17:56 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROC [dbo].[RetrieveINVHeadscode_stockt] @title nvarchar(255)
AS
SELECT RIGHT('0000000' + CONVERT(VARCHAR(7), IH.INVHEAD_ID), 7) AS 'INVENTORY Code',
PH.PARENTHEAD_CODE AS 'Parent Code', PH.PARENTHEAD_TITLE AS 'Parent Title', IH.INVHEAD_NAME AS 'INVENTORY Title',IH.INV_CODE_PARTNO 
AS 'INVENTORY CODE PART NO',IH.INV_SPECIFICATION_CHOICE AS 'INVENTORY SPECIFICATION',IH.INV_PICTURE_CHOICE AS 'INVENTORY PICTURE CHOICE',
IH.INVHEAD_ID,IH.INVHEAD_NAME,ISA.INV_SPECIFICATIONS, IA.STOCK_UNIT,  IA.RATE_PER_STOCK_UNIT,
 IA.RATE_PRICE_STOCK_UNIT,  IA.BALANCE_STOCK_UNIT
, IA.COST_STOCK_UNIT
FROM INVENTORY_HEADS AS IH 
INNER JOIN PARENT_HEADS AS PH
ON IH.INVPARENTHEAD_ID=PH.PARENTHEAD_ID
INNER JOIN INVENTORY_ATTRIBUTES AS IA
ON IH.INVHEAD_ID=IA.INVHEAD_ID
INNER JOIN INVENTORY_SPECIFICATIONS AS ISA
ON ISA.INVHEAD_ID=IA.INVHEAD_ID
where ph.PARENTHEAD_TITLE = @title
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'''A'' = Add, ''D'' = Deduct' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'TAX_TABLE', @level2type=N'COLUMN',@level2name=N'TAXACTION'
GO
USE [master]
GO
ALTER DATABASE [ADS_2] SET  READ_WRITE 
GO
