

CREATE PROC RetrieveINVHeadscode 
AS
SELECT RIGHT('0000000' + CONVERT(VARCHAR(7), IH.INVHEAD_ID), 7) AS 'INVENTORY Code',
PH.PARENTHEAD_CODE AS 'Parent Code', PH.PARENTHEAD_TITLE AS 'Parent Title', IH.INVHEAD_NAME AS 'INVENTORY Title',IH.INV_CODE_PARTNO 
AS 'INVENTORY CODE PART NO',IH.INV_SPECIFICATION_CHOICE AS 'INVENTORY SPECIFICATION',IH.INV_PICTURE_CHOICE AS 'INVENTORY PICTURE CHOICE',
IH.INVHEAD_ID,IH.INVHEAD_NAME,ISA.INV_SPECIFICATIONS, IA.STOCK_UNIT,  IA.PACKING_UNIT,  IA.LOOSE_UNIT,  IA.RATE_PER_LOOSE_UNIT,  IA.RATE_PER_STOCK_UNIT,  IA.RATE_PER_PACKING_UNIT,  IA.RATE_PRICE_LOOSE_UNIT,
 IA.RATE_PRICE_STOCK_UNIT,  IA.RATE_PRICE_PACKING_UNIT, IA.BALANCE_LOOSE_UNIT,  IA.BALANCE_STOCK_UNIT
IA.BALANCE_PACKING_UNIT, IA.COST_LOOSE_UNIT, IA.COST_STOCK_UNIT, IA.COST_PACKING_UNIT
FROM INVENTORY_HEADS AS IH 
INNER JOIN PARENT_HEADS AS PH
ON IH.INVPARENTHEAD_ID=PH.PARENTHEAD_ID
INNER JOIN INVENTORY_ATTRIBUTES AS IA
ON IH.INVHEAD_ID=IA.INVHEAD_ID
INNER JOIN INVENTORY_SPECIFICATIONS AS ISA
ON ISA.INVHEAD_ID=IA.INVHEAD_ID

GO



--2--Stock Unit Only-CODE

CREATE PROC RetrieveINVHeadscode_stock @Code nvarchar(15)
AS
SELECT RIGHT('0000000' + CONVERT(VARCHAR(7), IH.INVHEAD_ID), 7) AS 'INVENTORY Code',
PH.PARENTHEAD_CODE AS 'Parent Code', PH.PARENTHEAD_TITLE AS 'Parent Title', IH.INVHEAD_NAME AS 'INVENTORY Title',IH.INV_CODE_PARTNO 
AS 'INVENTORY CODE PART NO',IH.INV_SPECIFICATION_CHOICE AS 'INVENTORY SPECIFICATION',IH.INV_PICTURE_CHOICE AS 'INVENTORY PICTURE CHOICE',
IH.INVHEAD_ID,IH.INVHEAD_NAME,ISA.INV_SPECIFICATIONS, IA.STOCK_UNIT,  IA.RATE_PER_STOCK_UNIT,
 IA.RATE_PRICE_STOCK_UNIT,  IA.BALANCE_STOCK_UNIT
, IA.COST_STOCK_UNIT
FROM INVENTORY_HEADS AS IH 
INNER JOIN PARENT_HEADS AS PH
ON IH.INVPARENTHEAD_ID=PH.PARENTHEAD_ID
INNER JOIN INVENTORY_ATTRIBUTES AS IA
ON IH.INVHEAD_ID=IA.INVHEAD_ID
INNER JOIN INVENTORY_SPECIFICATIONS AS ISA
ON ISA.INVHEAD_ID=IA.INVHEAD_ID
where ph.PARENTHEAD_CODE = @Code
GO

EXEC RetrieveINVHeadscode_stock '010-010-000-000';


CREATE PROC RetrieveINVHeadscode_stockt @title nvarchar(255)
AS
SELECT RIGHT('0000000' + CONVERT(VARCHAR(7), IH.INVHEAD_ID), 7) AS 'INVENTORY Code',
PH.PARENTHEAD_CODE AS 'Parent Code', PH.PARENTHEAD_TITLE AS 'Parent Title', IH.INVHEAD_NAME AS 'INVENTORY Title',IH.INV_CODE_PARTNO 
AS 'INVENTORY CODE PART NO',IH.INV_SPECIFICATION_CHOICE AS 'INVENTORY SPECIFICATION',IH.INV_PICTURE_CHOICE AS 'INVENTORY PICTURE CHOICE',
IH.INVHEAD_ID,IH.INVHEAD_NAME,ISA.INV_SPECIFICATIONS, IA.STOCK_UNIT,  IA.RATE_PER_STOCK_UNIT,
 IA.RATE_PRICE_STOCK_UNIT,  IA.BALANCE_STOCK_UNIT
, IA.COST_STOCK_UNIT
FROM INVENTORY_HEADS AS IH 
INNER JOIN PARENT_HEADS AS PH
ON IH.INVPARENTHEAD_ID=PH.PARENTHEAD_ID
INNER JOIN INVENTORY_ATTRIBUTES AS IA
ON IH.INVHEAD_ID=IA.INVHEAD_ID
INNER JOIN INVENTORY_SPECIFICATIONS AS ISA
ON ISA.INVHEAD_ID=IA.INVHEAD_ID
where ph.PARENTHEAD_TITLE = @title
GO


--2--packing Unit Only-CODE

CREATE PROC RetrieveINVHeadscode_packing @Code nvarchar(15)
AS
SELECT RIGHT('0000000' + CONVERT(VARCHAR(7), IH.INVHEAD_ID), 7) AS 'INVENTORY Code',
PH.PARENTHEAD_CODE AS 'Parent Code', PH.PARENTHEAD_TITLE AS 'Parent Title', IH.INVHEAD_NAME AS 'INVENTORY Title',IH.INV_CODE_PARTNO 
AS 'INVENTORY CODE PART NO',IH.INV_SPECIFICATION_CHOICE AS 'INVENTORY SPECIFICATION',IH.INV_PICTURE_CHOICE AS 'INVENTORY PICTURE CHOICE',
IH.INVHEAD_ID,IH.INVHEAD_NAME,ISA.INV_SPECIFICATIONS, IA.LOOSE_UNIT,  IA.RATE_PER_LOOSE_UNIT,
 IA.RATE_PRICE_LOOSE_UNIT,  IA.BALANCE_LOOSE_UNIT
FROM INVENTORY_HEADS AS IH 
INNER JOIN PARENT_HEADS AS PH
ON IH.INVPARENTHEAD_ID=PH.PARENTHEAD_ID
INNER JOIN INVENTORY_ATTRIBUTES AS IA
ON IH.INVHEAD_ID=IA.INVHEAD_ID
INNER JOIN INVENTORY_SPECIFICATIONS AS ISA
ON ISA.INVHEAD_ID=IA.INVHEAD_ID
where ph.PARENTHEAD_CODE = @Code
GO

CREATE PROC RetrieveINVHeadscode_packingt @title nvarchar(255)
AS
SELECT RIGHT('0000000' + CONVERT(VARCHAR(7), IH.INVHEAD_ID), 7) AS 'INVENTORY Code',
PH.PARENTHEAD_CODE AS 'Parent Code', PH.PARENTHEAD_TITLE AS 'Parent Title', IH.INVHEAD_NAME AS 'INVENTORY Title',IH.INV_CODE_PARTNO 
AS 'INVENTORY CODE PART NO',IH.INV_SPECIFICATION_CHOICE AS 'INVENTORY SPECIFICATION',IH.INV_PICTURE_CHOICE AS 'INVENTORY PICTURE CHOICE',
IH.INVHEAD_ID,IH.INVHEAD_NAME,ISA.INV_SPECIFICATIONS, IA.LOOSE_UNIT,  IA.RATE_PER_LOOSE_UNIT,
 IA.RATE_PRICE_LOOSE_UNIT,  IA.BALANCE_LOOSE_UNIT
FROM INVENTORY_HEADS AS IH 
INNER JOIN PARENT_HEADS AS PH
ON IH.INVPARENTHEAD_ID=PH.PARENTHEAD_ID
INNER JOIN INVENTORY_ATTRIBUTES AS IA
ON IH.INVHEAD_ID=IA.INVHEAD_ID
INNER JOIN INVENTORY_SPECIFICATIONS AS ISA
ON ISA.INVHEAD_ID=IA.INVHEAD_ID
where ph.PARENTHEAD_TITLE = @title
GO


--2--LOOSE Unit Only-CODE

CREATE PROC RetrieveINVHeadscode_loose @Code nvarchar(15)
AS
SELECT RIGHT('0000000' + CONVERT(VARCHAR(7), IH.INVHEAD_ID), 7) AS 'INVENTORY Code',
PH.PARENTHEAD_CODE AS 'Parent Code', PH.PARENTHEAD_TITLE AS 'Parent Title', IH.INVHEAD_NAME AS 'INVENTORY Title',IH.INV_CODE_PARTNO 
AS 'INVENTORY CODE PART NO',IH.INV_SPECIFICATION_CHOICE AS 'INVENTORY SPECIFICATION',IH.INV_PICTURE_CHOICE AS 'INVENTORY PICTURE CHOICE',
IH.INVHEAD_ID,IH.INVHEAD_NAME,ISA.INV_SPECIFICATIONS, IA.LOOSE_UNIT,  IA.RATE_PER_LOOSE_UNIT,
 IA.RATE_PER_LOOSE_UNIT,  IA.BALANCE_LOOSE_UNIT
, IA.COST_LOOSE_UNIT
FROM INVENTORY_HEADS AS IH 
INNER JOIN PARENT_HEADS AS PH
ON IH.INVHEAD_ID=PH.PARENTHEAD_ID
INNER JOIN INVENTORY_ATTRIBUTES AS IA
ON IH.INVHEAD_ID=IA.INVHEAD_ID
INNER JOIN INVENTORY_SPECIFICATIONS AS ISA
ON ISA.INVHEAD_ID=IA.INVHEAD_ID
where ph.PARENTHEAD_CODE = @Code
GO

CREATE PROC RetrieveINVHeadscode_looset @title nvarchar(255)
AS
SELECT RIGHT('0000000' + CONVERT(VARCHAR(7), IH.INVHEAD_ID), 7) AS 'INVENTORY Code',
PH.PARENTHEAD_CODE AS 'Parent Code', PH.PARENTHEAD_TITLE AS 'Parent Title', IH.INVHEAD_NAME AS 'INVENTORY Title',IH.INV_CODE_PARTNO 
AS 'INVENTORY CODE PART NO',IH.INV_SPECIFICATION_CHOICE AS 'INVENTORY SPECIFICATION',IH.INV_PICTURE_CHOICE AS 'INVENTORY PICTURE CHOICE',
IH.INVHEAD_ID,IH.INVHEAD_NAME,ISA.INV_SPECIFICATIONS, IA.LOOSE_UNIT,  IA.RATE_PER_LOOSE_UNIT,
 IA.RATE_PER_LOOSE_UNIT,  IA.BALANCE_LOOSE_UNIT
, IA.COST_LOOSE_UNIT
FROM INVENTORY_HEADS AS IH 
INNER JOIN PARENT_HEADS AS PH
ON IH.INVPARENTHEAD_ID=PH.PARENTHEAD_ID
INNER JOIN INVENTORY_ATTRIBUTES AS IA
ON IH.INVHEAD_ID=IA.INVHEAD_ID
INNER JOIN INVENTORY_SPECIFICATIONS AS ISA
ON ISA.INVHEAD_ID=IA.INVHEAD_ID
where ph.PARENTHEAD_TITLE = @title
GO

--2--Stock Unit Loose Unit

CREATE PROC RetrieveINVHeadscode_stockloose @Code nvarchar(15)
AS
SELECT RIGHT('0000000' + CONVERT(VARCHAR(7), IH.INVHEAD_ID), 7) AS 'INVENTORY Code',
PH.PARENTHEAD_CODE AS 'Parent Code', PH.PARENTHEAD_TITLE AS 'Parent Title', IH.INVHEAD_NAME AS 'INVENTORY Title',IH.INV_CODE_PARTNO 
AS 'INVENTORY CODE PART NO',IH.INV_SPECIFICATION_CHOICE AS 'INVENTORY SPECIFICATION',IH.INV_PICTURE_CHOICE AS 'INVENTORY PICTURE CHOICE',
ISA.INV_SPECIFICATIONS, 
IA.STOCK_UNIT, IA.LOOSE_UNIT, IA.RATE_PER_LOOSE_UNIT, IA.RATE_PER_STOCK_UNIT, IA.RATE_PRICE_LOOSE_UNIT, IA.RATE_PRICE_STOCK_UNIT,
IA.BALANCE_LOOSE_UNIT,	IA.BALANCE_STOCK_UNIT, IA.COST_LOOSE_UNIT, IA.COST_STOCK_UNIT
FROM INVENTORY_HEADS AS IH 
INNER JOIN PARENT_HEADS AS PH
ON IH.INVPARENTHEAD_ID=PH.PARENTHEAD_ID
INNER JOIN INVENTORY_ATTRIBUTES AS IA
ON IH.INVHEAD_ID=IA.INVHEAD_ID
INNER JOIN INVENTORY_SPECIFICATIONS AS ISA
ON ISA.INVHEAD_ID=IA.INVHEAD_ID
where ph.PARENTHEAD_CODE = @Code
GO

CREATE PROC RetrieveINVHeadscode_stocklooset @title nvarchar(255)
AS
SELECT RIGHT('0000000' + CONVERT(VARCHAR(7), IH.INVHEAD_ID), 7) AS 'INVENTORY Code',
PH.PARENTHEAD_CODE AS 'Parent Code', PH.PARENTHEAD_TITLE AS 'Parent Title', IH.INVHEAD_NAME AS 'INVENTORY Title',IH.INV_CODE_PARTNO 
AS 'INVENTORY CODE PART NO',IH.INV_SPECIFICATION_CHOICE AS 'INVENTORY SPECIFICATION',IH.INV_PICTURE_CHOICE AS 'INVENTORY PICTURE CHOICE',
ISA.INV_SPECIFICATIONS, 
IA.STOCK_UNIT, IA.LOOSE_UNIT, IA.RATE_PER_LOOSE_UNIT, IA.RATE_PER_STOCK_UNIT, IA.RATE_PRICE_LOOSE_UNIT, IA.RATE_PRICE_STOCK_UNIT,
IA.BALANCE_LOOSE_UNIT,	IA.BALANCE_STOCK_UNIT, IA.COST_LOOSE_UNIT, IA.COST_STOCK_UNIT
FROM INVENTORY_HEADS AS IH 
INNER JOIN PARENT_HEADS AS PH
ON IH.INVPARENTHEAD_ID=PH.PARENTHEAD_ID
INNER JOIN INVENTORY_ATTRIBUTES AS IA
ON IH.INVHEAD_ID=IA.INVHEAD_ID
INNER JOIN INVENTORY_SPECIFICATIONS AS ISA
ON ISA.INVHEAD_ID=IA.INVHEAD_ID
where ph.PARENTHEAD_TITLE = @title
GO

--2--Stock Unit Packing Unit

CREATE PROC RetrieveINVHeadscode_stockpacking @Code nvarchar(15)
AS
SELECT RIGHT('0000000' + CONVERT(VARCHAR(7), IH.INVHEAD_ID), 7) AS 'INVENTORY Code',
PH.PARENTHEAD_CODE AS 'Parent Code', PH.PARENTHEAD_TITLE AS 'Parent Title', IH.INVHEAD_NAME AS 'INVENTORY Title',IH.INV_CODE_PARTNO 
AS 'INVENTORY CODE PART NO',IH.INV_SPECIFICATION_CHOICE AS 'INVENTORY SPECIFICATION',IH.INV_PICTURE_CHOICE AS 'INVENTORY PICTURE CHOICE',
ISA.INV_SPECIFICATIONS, 
IA.STOCK_UNIT, IA.PACKING_UNIT, IA.RATE_PER_STOCK_UNIT, IA.RATE_PER_PACKING_UNIT, IA.RATE_PRICE_STOCK_UNIT, IA.RATE_PRICE_PACKING_UNIT,
IA.BALANCE_STOCK_UNIT, IA.BALANCE_PACKING_UNIT, IA.COST_STOCK_UNIT, IA.COST_PACKING_UNIT
FROM INVENTORY_HEADS AS IH 
INNER JOIN PARENT_HEADS AS PH
ON IH.INVPARENTHEAD_ID=PH.PARENTHEAD_ID
INNER JOIN INVENTORY_ATTRIBUTES AS IA
ON IH.INVHEAD_ID=IA.INVHEAD_ID
INNER JOIN INVENTORY_SPECIFICATIONS AS ISA
ON ISA.INVHEAD_ID=IA.INVHEAD_ID
where ph.PARENTHEAD_CODE = @Code
GO

CREATE PROC RetrieveINVHeadscode_stockpackingt @title nvarchar(255)
AS
SELECT RIGHT('0000000' + CONVERT(VARCHAR(7), IH.INVHEAD_ID), 7) AS 'INVENTORY Code',
PH.PARENTHEAD_CODE AS 'Parent Code', PH.PARENTHEAD_TITLE AS 'Parent Title', IH.INVHEAD_NAME AS 'INVENTORY Title',IH.INV_CODE_PARTNO 
AS 'INVENTORY CODE PART NO',IH.INV_SPECIFICATION_CHOICE AS 'INVENTORY SPECIFICATION',IH.INV_PICTURE_CHOICE AS 'INVENTORY PICTURE CHOICE',
ISA.INV_SPECIFICATIONS, 
IA.STOCK_UNIT, IA.PACKING_UNIT, IA.RATE_PER_STOCK_UNIT, IA.RATE_PER_PACKING_UNIT, IA.RATE_PRICE_STOCK_UNIT, IA.RATE_PRICE_PACKING_UNIT,
IA.BALANCE_STOCK_UNIT, IA.BALANCE_PACKING_UNIT, IA.COST_STOCK_UNIT, IA.COST_PACKING_UNIT
FROM INVENTORY_HEADS AS IH 
INNER JOIN PARENT_HEADS AS PH
ON IH.INVPARENTHEAD_ID=PH.PARENTHEAD_ID
INNER JOIN INVENTORY_ATTRIBUTES AS IA
ON IH.INVHEAD_ID=IA.INVHEAD_ID
INNER JOIN INVENTORY_SPECIFICATIONS AS ISA
ON ISA.INVHEAD_ID=IA.INVHEAD_ID
where ph.PARENTHEAD_TITLE = @title
GO


--2--Packing Unit Loose Unit

CREATE PROC RetrieveINVHeadscode_packingloose @Code nvarchar(15)
AS
SELECT RIGHT('0000000' + CONVERT(VARCHAR(7), IH.INVHEAD_ID), 7) AS 'INVENTORY Code',
PH.PARENTHEAD_CODE AS 'Parent Code', PH.PARENTHEAD_TITLE AS 'Parent Title', IH.INVHEAD_NAME AS 'INVENTORY Title',IH.INV_CODE_PARTNO 
AS 'INVENTORY CODE PART NO',IH.INV_SPECIFICATION_CHOICE AS 'INVENTORY SPECIFICATION',IH.INV_PICTURE_CHOICE AS 'INVENTORY PICTURE CHOICE',
ISA.INV_SPECIFICATIONS, 
		IA.PACKING_UNIT, IA.LOOSE_UNIT, IA.RATE_PER_LOOSE_UNIT, IA.RATE_PER_PACKING_UNIT, IA.RATE_PRICE_LOOSE_UNIT, IA.RATE_PRICE_PACKING_UNIT, 
		IA.BALANCE_LOOSE_UNIT, IA.BALANCE_PACKING_UNIT, IA.COST_LOOSE_UNIT, IA.COST_PACKING_UNIT
FROM INVENTORY_HEADS AS IH 
INNER JOIN PARENT_HEADS AS PH
ON IH.INVPARENTHEAD_ID=PH.PARENTHEAD_ID
INNER JOIN INVENTORY_ATTRIBUTES AS IA
ON IH.INVHEAD_ID=IA.INVHEAD_ID
INNER JOIN INVENTORY_SPECIFICATIONS AS ISA
ON ISA.INVHEAD_ID=IA.INVHEAD_ID
where ph.PARENTHEAD_CODE = @Code
GO


CREATE PROC RetrieveINVHeadscode_packinglooset @title nvarchar(255)
AS
SELECT RIGHT('0000000' + CONVERT(VARCHAR(7), IH.INVHEAD_ID), 7) AS 'INVENTORY Code',
PH.PARENTHEAD_CODE AS 'Parent Code', PH.PARENTHEAD_TITLE AS 'Parent Title', IH.INVHEAD_NAME AS 'INVENTORY Title',IH.INV_CODE_PARTNO 
AS 'INVENTORY CODE PART NO',IH.INV_SPECIFICATION_CHOICE AS 'INVENTORY SPECIFICATION',IH.INV_PICTURE_CHOICE AS 'INVENTORY PICTURE CHOICE',
ISA.INV_SPECIFICATIONS, 
		IA.PACKING_UNIT, IA.LOOSE_UNIT, IA.RATE_PER_LOOSE_UNIT, IA.RATE_PER_PACKING_UNIT, IA.RATE_PRICE_LOOSE_UNIT, IA.RATE_PRICE_PACKING_UNIT, 
		IA.BALANCE_LOOSE_UNIT, IA.BALANCE_PACKING_UNIT, IA.COST_LOOSE_UNIT, IA.COST_PACKING_UNIT
FROM INVENTORY_HEADS AS IH 
INNER JOIN PARENT_HEADS AS PH
ON IH.INVPARENTHEAD_ID=PH.PARENTHEAD_ID
INNER JOIN INVENTORY_ATTRIBUTES AS IA
ON IH.INVHEAD_ID=IA.INVHEAD_ID
INNER JOIN INVENTORY_SPECIFICATIONS AS ISA
ON ISA.INVHEAD_ID=IA.INVHEAD_ID
where ph.PARENTHEAD_TITLE = @title
GO







EXEC RetrieveINVHeadscode ;
EXEC RetrieveINVHeadscode_stock '010-010-000-000';


EXEC RetrieveINVHeadscode_packing '010-090-000-000';
EXEC RetrieveINVHeadscode_loose  '010-090-000-000';
EXEC RetrieveINVHeadscode_stockloose'010-090-000-000';
EXEC RetrieveINVHeadscode_stockpacking '010-090-000-000';
EXEC RetrieveINVHeadscode_packingloose '010-090-000-000';


EXEC RetrieveINVHeadscode_stockt '010-090-000-000';
EXEC RetrieveINVHeadscode_packingt '010-090-000-000';
EXEC RetrieveINVHeadscode_looset  '010-090-000-000';
EXEC RetrieveINVHeadscode_stocklooset'010-090-000-000';
EXEC RetrieveINVHeadscode_stockpackingt '010-090-000-000';
EXEC RetrieveINVHeadscode_packinglooset '010-090-000-000';