--1--FULL Version--
CREATE Proc InventoryAttributesGivenParentHead @Code nvarchar(15)
AS
Select  INVENTORY_ATTRIBUTES.INVHEAD_ID,INVENTORY_HEADS.INVHEAD_NAME, INV_SPECIFICATIONS, STOCK_UNIT, PACKING_UNIT
      , LOOSE_UNIT, RATE_PER_LOOSE_UNIT, RATE_PER_STOCK_UNIT, RATE_PER_PACKING_UNIT, RATE_PRICE_LOOSE_UNIT
      , RATE_PRICE_STOCK_UNIT, RATE_PRICE_PACKING_UNIT, BALANCE_LOOSE_UNIT, BALANCE_STOCK_UNIT
	  , BALANCE_PACKING_UNIT, COST_LOOSE_UNIT, COST_STOCK_UNIT, COST_PACKING_UNIT
from INVENTORY_ATTRIBUTES 
INNER JOIN INVENTORY_HEADS ON INVENTORY_HEADS.INVHEAD_ID = INVENTORY_ATTRIBUTES.INVHEAD_ID
INNER JOIN INVENTORY_SPECIFICATIONS ON INVENTORY_HEADS.INVHEAD_ID = INVENTORY_SPECIFICATIONS.INVHEAD_ID
WHERE INVENTORY_HEADS.INVHEAD_ID IN (Select INVENTORY_HEADS.INVHEAD_ID from INVENTORY_HEADS 
									INNER JOIN PARENT_HEADS
									ON INVENTORY_HEADS.INVPARENTHEAD_ID = PARENT_HEADS.PARENTHEAD_ID
									WHERE PARENT_HEADS.PARENTHEAD_CODE = @Code);
GO


--2--Stock Unit Only

CREATE Proc InventoryAttributesGivenParentHead_Stock @Code nvarchar(15)
AS
Select  INVENTORY_ATTRIBUTES.INVHEAD_ID,INVENTORY_HEADS.INVHEAD_NAME, INV_SPECIFICATIONS, 
		STOCK_UNIT, RATE_PER_STOCK_UNIT, RATE_PRICE_STOCK_UNIT, BALANCE_STOCK_UNIT, COST_STOCK_UNIT
from INVENTORY_ATTRIBUTES 
INNER JOIN INVENTORY_HEADS ON INVENTORY_HEADS.INVHEAD_ID = INVENTORY_ATTRIBUTES.INVHEAD_ID
INNER JOIN INVENTORY_SPECIFICATIONS ON INVENTORY_HEADS.INVHEAD_ID = INVENTORY_SPECIFICATIONS.INVHEAD_ID
WHERE INVENTORY_HEADS.INVHEAD_ID IN (Select INVENTORY_HEADS.INVHEAD_ID from INVENTORY_HEADS 
									INNER JOIN PARENT_HEADS
									ON INVENTORY_HEADS.INVPARENTHEAD_ID = PARENT_HEADS.PARENTHEAD_ID
									WHERE PARENT_HEADS.PARENTHEAD_CODE = @Code);
GO

--3--Packing Unit Only
CREATE Proc InventoryAttributesGivenParentHead_Packing @Code nvarchar(15)
AS
Select  INVENTORY_ATTRIBUTES.INVHEAD_ID,INVENTORY_HEADS.INVHEAD_NAME, INV_SPECIFICATIONS, 
		PACKING_UNIT, RATE_PER_PACKING_UNIT, RATE_PRICE_PACKING_UNIT, BALANCE_PACKING_UNIT, COST_PACKING_UNIT
from INVENTORY_ATTRIBUTES 
INNER JOIN INVENTORY_HEADS ON INVENTORY_HEADS.INVHEAD_ID = INVENTORY_ATTRIBUTES.INVHEAD_ID
INNER JOIN INVENTORY_SPECIFICATIONS ON INVENTORY_HEADS.INVHEAD_ID = INVENTORY_SPECIFICATIONS.INVHEAD_ID
WHERE INVENTORY_HEADS.INVHEAD_ID IN (Select INVENTORY_HEADS.INVHEAD_ID from INVENTORY_HEADS 
									INNER JOIN PARENT_HEADS
									ON INVENTORY_HEADS.INVPARENTHEAD_ID = PARENT_HEADS.PARENTHEAD_ID
									WHERE PARENT_HEADS.PARENTHEAD_CODE = @Code);
GO

--4--Loose Unit Only 
CREATE Proc InventoryAttributesGivenParentHead_Loose @Code nvarchar(15)
AS
Select  INVENTORY_ATTRIBUTES.INVHEAD_ID,INVENTORY_HEADS.INVHEAD_NAME, INV_SPECIFICATIONS,
		LOOSE_UNIT, RATE_PER_LOOSE_UNIT, RATE_PRICE_LOOSE_UNIT, BALANCE_LOOSE_UNIT, COST_LOOSE_UNIT
from INVENTORY_ATTRIBUTES 
INNER JOIN INVENTORY_HEADS ON INVENTORY_HEADS.INVHEAD_ID = INVENTORY_ATTRIBUTES.INVHEAD_ID
INNER JOIN INVENTORY_SPECIFICATIONS ON INVENTORY_HEADS.INVHEAD_ID = INVENTORY_SPECIFICATIONS.INVHEAD_ID
WHERE INVENTORY_HEADS.INVHEAD_ID IN (Select INVENTORY_HEADS.INVHEAD_ID from INVENTORY_HEADS 
									INNER JOIN PARENT_HEADS
									ON INVENTORY_HEADS.INVPARENTHEAD_ID = PARENT_HEADS.PARENTHEAD_ID
									WHERE PARENT_HEADS.PARENTHEAD_CODE = @Code);
GO

--5--Stock Unit Loose Unit
CREATE Proc InventoryAttributesGivenParentHead_StockLoose @Code nvarchar(15)
AS
Select  INVENTORY_ATTRIBUTES.INVHEAD_ID,INVENTORY_HEADS.INVHEAD_NAME, INV_SPECIFICATIONS, 
		STOCK_UNIT, LOOSE_UNIT, RATE_PER_LOOSE_UNIT, RATE_PER_STOCK_UNIT, RATE_PRICE_LOOSE_UNIT, RATE_PRICE_STOCK_UNIT,
		BALANCE_LOOSE_UNIT,	BALANCE_STOCK_UNIT, COST_LOOSE_UNIT, COST_STOCK_UNIT
from INVENTORY_ATTRIBUTES 
INNER JOIN INVENTORY_HEADS ON INVENTORY_HEADS.INVHEAD_ID = INVENTORY_ATTRIBUTES.INVHEAD_ID
INNER JOIN INVENTORY_SPECIFICATIONS ON INVENTORY_HEADS.INVHEAD_ID = INVENTORY_SPECIFICATIONS.INVHEAD_ID
WHERE INVENTORY_HEADS.INVHEAD_ID IN (Select INVENTORY_HEADS.INVHEAD_ID from INVENTORY_HEADS 
									INNER JOIN PARENT_HEADS
									ON INVENTORY_HEADS.INVPARENTHEAD_ID = PARENT_HEADS.PARENTHEAD_ID
									WHERE PARENT_HEADS.PARENTHEAD_CODE = @Code);
GO

--6--Stock Unit Packing Unit
CREATE Proc InventoryAttributesGivenParentHead_StockPacking @Code nvarchar(15)
AS
Select  INVENTORY_ATTRIBUTES.INVHEAD_ID,INVENTORY_HEADS.INVHEAD_NAME, INV_SPECIFICATIONS, 
		STOCK_UNIT, PACKING_UNIT, RATE_PER_STOCK_UNIT, RATE_PER_PACKING_UNIT, RATE_PRICE_STOCK_UNIT, RATE_PRICE_PACKING_UNIT,
		BALANCE_STOCK_UNIT, BALANCE_PACKING_UNIT, COST_STOCK_UNIT, COST_PACKING_UNIT
from INVENTORY_ATTRIBUTES 
INNER JOIN INVENTORY_HEADS ON INVENTORY_HEADS.INVHEAD_ID = INVENTORY_ATTRIBUTES.INVHEAD_ID
INNER JOIN INVENTORY_SPECIFICATIONS ON INVENTORY_HEADS.INVHEAD_ID = INVENTORY_SPECIFICATIONS.INVHEAD_ID
WHERE INVENTORY_HEADS.INVHEAD_ID IN (Select INVENTORY_HEADS.INVHEAD_ID from INVENTORY_HEADS 
									INNER JOIN PARENT_HEADS
									ON INVENTORY_HEADS.INVPARENTHEAD_ID = PARENT_HEADS.PARENTHEAD_ID
									WHERE PARENT_HEADS.PARENTHEAD_CODE = @Code);
GO

--7--Packing Unit Loose Unit

CREATE Proc InventoryAttributesGivenParentHead_PackingLoose @Code nvarchar(15)
AS
Select  INVENTORY_ATTRIBUTES.INVHEAD_ID,INVENTORY_HEADS.INVHEAD_NAME, INV_SPECIFICATIONS, 
		PACKING_UNIT, LOOSE_UNIT, RATE_PER_LOOSE_UNIT, RATE_PER_PACKING_UNIT, RATE_PRICE_LOOSE_UNIT, RATE_PRICE_PACKING_UNIT, 
		BALANCE_LOOSE_UNIT, BALANCE_PACKING_UNIT, COST_LOOSE_UNIT, COST_PACKING_UNIT
from INVENTORY_ATTRIBUTES 
INNER JOIN INVENTORY_HEADS ON INVENTORY_HEADS.INVHEAD_ID = INVENTORY_ATTRIBUTES.INVHEAD_ID
INNER JOIN INVENTORY_SPECIFICATIONS ON INVENTORY_HEADS.INVHEAD_ID = INVENTORY_SPECIFICATIONS.INVHEAD_ID
WHERE INVENTORY_HEADS.INVHEAD_ID IN (Select INVENTORY_HEADS.INVHEAD_ID from INVENTORY_HEADS 
									INNER JOIN PARENT_HEADS
									ON INVENTORY_HEADS.INVPARENTHEAD_ID = PARENT_HEADS.PARENTHEAD_ID
									WHERE PARENT_HEADS.PARENTHEAD_CODE = @Code);
GO





EXEC InventoryAttributesGivenParentHead '010-090-000-000';
EXEC InventoryAttributesGivenParentHead_Stock '010-090-000-000';
EXEC InventoryAttributesGivenParentHead_Loose '010-090-000-000';
EXEC InventoryAttributesGivenParentHead_Packing '010-090-000-000';
EXEC InventoryAttributesGivenParentHead_StockLoose'010-090-000-000';
EXEC InventoryAttributesGivenParentHead_StockPacking '010-090-000-000';
EXEC InventoryAttributesGivenParentHead_PackingLoose '010-090-000-000';