SELECT PH.PARENTHEAD_TITLE,IH.INVHEAD_ID,IH.INVHEAD_NAME, ISP.INV_SPECIFICATIONS, IA.BALANCE_LOOSE_UNIT, 
IA.BALANCE_PACKING_UNIT, IA.BALANCE_STOCK_UNIT, IA.CONSUMPTION_DR_ACC,IA.COST_LOOSE_UNIT,IA.COST_PACKING_UNIT,IA.COST_STOCK_UNIT,
IA.LOOSE_UNIT, IA.PACKING_UNIT,IA.PRODUCTION_DR_ACC,IA.PURCHASE_DR_ACC,IA.RATE_PER_LOOSE_UNIT,IA.RATE_PER_PACKING_UNIT, IA.RATE_PER_STOCK_UNIT,IA.RATE_PRICE_LOOSE_UNIT,IA.RATE_PRICE_PACKING_UNIT,
IA.RATE_PRICE_STOCK_UNIT,IA.SALE_CR_ACC,IA.STOCK_UNIT FROM PARENT_HEADS AS PH
INNER JOIN INVENTORY_HEADS AS IH on PH.PARENTHEAD_ID = IH.INVPARENTHEAD_ID
INNER JOIN INVENTORY_SPECIFICATIONS AS ISP on IH.INVHEAD_ID = ISP.INVHEAD_ID
INNER JOIN INVENTORY_ATTRIBUTES AS IA on IA.INVHEAD_ID = IH.INVHEAD_ID

