CREATE PROC RetrieveAccHeads
AS
SELECT RIGHT('0000000' + CONVERT(VARCHAR(7), AH.ACCHEAD_ID), 7) AS 'Account Code',
PH.PARENTHEAD_CODE AS 'Parent Code', PH.PARENTHEAD_TITLE AS 'Parent Title', AH.ACCHEAD_NAME AS 'Account Title', AH.ADDCARD_CHOICE AS 'Address',
AH.ATTRIBUTE_CHOICE AS 'Attributes', AH.DEPCARD_CHOICE AS 'Depriciation', AH.PICTURE_CHOICE AS 'Depriciation Yearly Rate'
FROM ACCOUNT_HEADS AS AH 
INNER JOIN PARENT_HEADS AS PH
ON AH.ACCPARENTHEAD_ID=PH.PARENTHEAD_ID
GO

Execute RetrieveAccHeads;

SELECT RIGHT('0000000' + CONVERT(VARCHAR(7), AH.ACCHEAD_ID), 7) AS 'Account Code',
PH.PARENTHEAD_CODE AS 'Parent Code', PH.PARENTHEAD_TITLE AS 'Parent Title', AH.ACCHEAD_NAME AS 'Account Title', AH.ADDCARD_CHOICE AS 'Address',
AH.ATTRIBUTE_CHOICE AS 'Attributes', AH.DEPCARD_CHOICE AS 'Depriciation', AH.PICTURE_CHOICE AS 'Depriciation Yearly Rate'
FROM ACCOUNT_HEADS AS AH 
INNER JOIN PARENT_HEADS AS PH
ON AH.ACCPARENTHEAD_ID=PH.PARENTHEAD_ID