--SELECT PARENT_HEADS.PARENTHEAD_TITLE, ACCOUNT_HEADS.ACCHEAD_NAME
--FROM PARENT_HEADS
--INNER JOIN ACCOUNT_HEADS
--ON PARENT_HEADS.PARENTHEAD_ID =ACCOUNT_HEADS.ACCPARENTHEAD_ID;



--CREATE PROCEDURE Count_Heads @Code nvarchar(15), @TypeACCINV nvarchar(1), @TypeBALINC nvarchar(1)
--AS
--SELECT COUNT(PARENTHEAD_CODE)
--FROM PARENT_HEADS
--WHERE PARENTHEAD_CODE LIKE @Code AND PARENTHEAD_TYPE = @TypeACCINV AND PARENTHEAD_TYPEII = @TypeBALINC 
--GO

--EXEC Count_Heads '010-%-000-000','A','B';

--CREATE PROCEDURE Heads_CodeTitle @Code nvarchar(15), @TypeACCINV nvarchar(1), @TypeBALINC nvarchar(1)
--AS
--SELECT PARENTHEAD_CODE, PARENTHEAD_TITLE
--FROM PARENT_HEADS
--WHERE PARENTHEAD_CODE LIKE @Code AND PARENTHEAD_TYPE = @TypeACCINV AND PARENTHEAD_TYPEII = @TypeBALINC 
--GO

EXEC Count_Heads '010-010-%-000','A','B';
EXEC Heads_CodeTitle '010-010-%-000','A','B';
