--Select * from ACCOUNT_HEADS
--WHERE ACCPARENTHEAD_ID = 8;
--Select * from PARENT_HEADS
--WHERE PARENTHEAD_ID = 8;

--Select ACCOUNT_HEADS.ACCHEAD_ID, ACCOUNT_HEADS.ACCHEAD_NAME from ACCOUNT_HEADS 
--INNER JOIN PARENT_HEADS
--ON ACCOUNT_HEADS.ACCPARENTHEAD_ID = PARENT_HEADS.PARENTHEAD_ID
--WHERE PARENT_HEADS.PARENTHEAD_CODE = '010-007-000-000'; 

--CREATE PROC AccountHeadGivenParentHead @Code nvarchar(15)
--AS
--Select ACCOUNT_HEADS.ACCHEAD_ID, ACCOUNT_HEADS.ACCHEAD_NAME from ACCOUNT_HEADS 
--INNER JOIN PARENT_HEADS
--ON ACCOUNT_HEADS.ACCPARENTHEAD_ID = PARENT_HEADS.PARENTHEAD_ID
--WHERE PARENT_HEADS.PARENTHEAD_CODE = @Code;
--GO

CREATE PROC InventoryHeadGivenParentHead @Code nvarchar(15)
AS
Select INVENTORY_HEADS.INVHEAD_ID, INVENTORY_HEADS.INVHEAD_NAME from INVENTORY_HEADS 
INNER JOIN PARENT_HEADS
ON INVENTORY_HEADS.INVPARENTHEAD_ID = PARENT_HEADS.PARENTHEAD_ID
WHERE PARENT_HEADS.PARENTHEAD_CODE = @Code;
Go

Execute InventoryHeadGivenParentHead '010-000-000-000';

EXEC AccountHeadGivenParentHead '000-000-000-000';