
--ALTER TABLE PARENT_HEADS
--ADD PARENTHEAD_TYPEII nvarchar(1);

--UPDATE PARENT_HEADS
--SET PARENTHEAD_TYPEII = 'B'
--WHERE PARENTHEAD_ID < 70;

--UPDATE PARENT_HEADS
--SET PARENTHEAD_TYPEII = 'I'
--WHERE PARENTHEAD_ID >= 70 AND PARENTHEAD_ID <= 100;


--UPDATE PARENT_HEADS
--SET PARENTHEAD_TYPEII = 'B'
--WHERE PARENTHEAD_ID >= 102 AND PARENTHEAD_ID <= 130;